const Lang = {
    ActNot: 'Belum mulai',
    ActEnd: 'Berakhir',
    ok: 'Ya',
    GameB: 'Koin karnaval:',
    fiveTips: 'Selamat! Anda telah memenangkan hadiah berikut dalam 5 kali berturut-turut:',
    noCointTitle: 'Tidak bisa undian',
    noCoinsTips4: 'Saldo koin karnaval Anda tidak cukup untuk undian',
    noCoinsTips2: 'Cepat dapatkan koin karnaval!    ',
    noRank: 'Tidak dalam daftar',
    myScore: 'Nilai karnavalku:',
    lastRankScore: 'Nilai karnaval yang masih kurang masuk peringkat：',
    myScore2: 'Nilai penolong:',
    lastRankScore2: 'Sampai masuk peringkat masih kurang:',
    storeNum: 'Telah top up:',
    numTips2: 'Jauh di depan kedua:',
    numTips3: 'Untuk melebihi yang sebelumnya masih kurang:',
    numTips4: 'Untuk masuk perkingkat masih kuarng:',
    singUpNo: 'Gagal daftar',
    noData: 'Tidak ada data',
    happyScore: 'Nilai karnaval:',
    rankTips1: 'Nilai karnaval = jumlah koin karnavala yang digunakan',
    mvpTips1: 'Levelku:',
    mvpTips2: 'Nilai penolong:',
    mvpTips3: 'Nilai penolong=Nilai hadiah koin emas yang dikirimkan di nyanyian atau kamar karaoke setelah pendaftaran',
    mvpTips4: 'Nilai penolong mencapai <em>X</em> untuk diterima',
    mvpTips5: '(Yaitu meningkatkan ke level X)',
    mvpTips6: 'Berhasil diterima',
    mvpTips7: 'Hadiah yang sesuai telah dikirimkan ke akun Anda, silakan cek',
    // petTips1: '每收到一種禮物可解鎖一級獎勵 <br />已有<em>X</em> 位歌友收集齊6種禮物',
    day: 'day',
    loading: 'Memuat...',
    noPeople: 'Saat ini tidak ada penyanyi dalam peringkat, menunggu Anda!',
    // petTips2: '贈送者',
    // petTips3: '收集時間',
    // petTips4: '收集禮物',
    // petTips5: '暫無收集紀錄',
    // petTips6: '依據收到的 <em>N</em> 禮物數排名，第一名可獲得<em>S</em>禮物冠名權,前10名獲得豐厚獎勵',
    chuzTips1: '1. Hadiah ransel perlu diperbarui ke versi terbaru untuk digunakan    ',
    chuzTips2: '2. Hadiah peringkat acara akan dikirimkan dalam 14 hari kerja setelah acara berakhir    ',
    // chuzTips3: '2.排行獎勵將於聖誕節結束後14個工作日內派發完畢~',
    // actTips1: '以下活動指定時間段，21:00:00-21:10:00獲得的分數額外加成10%',
    taskTips1: 'Koin karnaval akan otomatis dimasukkan ke akun Anda saat tugas selesai, dan koin karnaval yang diperoleh setiap hari tidak akan dihapus.',
    taskTips2: 'Tugas harian',
    taskTips3: 'Tingkat kemajuan',
    taskTips4: 'Sudah',
    luckTips1: 'Selamat! Anda berhasil dapat',
    luckTips2: 'Waktu undian    ',
    luckTips3: 'Hadiah didapatkan    ',
    luckTips4: 'Catatan undian kosong, cepat dapatkan koin karnaval!    ',
    luckTips5: 'Tidak bisa undian    ',
    luckTips6: 'Anda belum mendaftar, tidak bisa undian. Silakan daftar!    ',
    // luckTips7: '歡卡為年度人物評選活動的投票券，可在年度人物評選活動中投出',
    luckTips8: 'Berlaku selama 7 hari',
    luckTips9: 'Berlaku selama 1 hari',
    // luckTips10: '歡卡為年度人物評選活動的投票券',
    luckTips11: 'Hadiah ransel berlaku selama 7 hari',
    luckTips12: 'Kupon bonus untuk top up berlaku selama 1 hari',
    luckTips13: 'Kupon bonus untuk sawer berlaku selama 1 hari',
}
export default Lang