export default {
    bg: require('./img/bg.png'),
    open_rank: require('./img/open_rank.png'),
    open_list: require('./img/open_list.png'),
    icon_befall: require('./img/icon_befall.png'),
    icon_bless: require('./img/icon_bless.png'),
    fate_befall:require('./img/fate_befall.png'),
    fate_bless:require('./img/fate_bless.png'),
    icon_rank_hot:require('./img/icon_rank_hot.png'),
    unopen:require('./img/unopen.png'),
    done:require('./img/done.png'),
    reward1:require('./img/reward1.png'),
    reward2:require('./img/reward2.png'),
    reward3:require('./img/reward3.png'),
    reward4:require('./img/reward4.png'),
    reward5:require('./img/reward5.png'),
    reward6:require('./img/reward6.png'),
    reward7:require('./img/reward7.png'),
    reward8:require('./img/reward8.png'),
    rule_reward1:require('./img/rule_reward1.png'),
    rule_reward2:require('./img/rule_reward2.png'),
    rule_reward3:require('./img/rule_reward3.png'),
    week_reward1:require('./img/week_reward1.png'),
    week_reward2:require('./img/week_reward2.png'),
    week_reward3:require('./img/week_reward3.png'),
    week_reward4:require('./img/week_reward4.png'),
    week_reward5:require('./img/week_reward5.png'),
}