export default {
    title: "印尼小音奇緣",
    befall_title: "降臨排名",
    bless_title: "祝福排名",
    rule_title: "小音奇緣規則",
    loading: "加載中...",
    no_data: "暫無數據",
    record_title: "奇緣記錄",
    rank_title: "奇緣榜單",
    openComeList: "排名",
    value: "奇緣值",
    dist: "達成還需",
    tips: "增加房間金幣流水獲得奇緣值，進度達成將觸發獎勵",
    sendRoomGift: "送禮增加奇緣值",
    tab1: "房間激勵",
    tab2: "貢獻最多者",
    tab3: "最後貢獻者",
    cell1: {
        title: "小音降臨",
        tips: "房間稱號30分鐘",
    },
    cell2: {
        title: "幸運水晶球",
        tips: "房間占卜獎勵",
    },
    cell3: {
        title: "飛碟音",
        tips: "奇緣禮物x5",
    },
    cell4: {
        title: "小音奇緣",
        tips: "奇緣勛章1天",
    },
    h_cell1: {
        title: "熱門推薦",
        tips: "流量曝光60分鐘",
    },
    h_cell2: {
        title: "幸運水晶球",
        tips: "房間占卜獎勵",
    },
    h_cell3: {
        title: "音為有你",
        tips: "稀有禮物x1",
    },
    h_cell4: {
        title: "飛船",
        tips: "稀有頭像框1天",
    },
    my_room: "本房間",
    come_no_data: "暫時沒有玩家上榜",
    come_list_tips:
        "房間內贈送金幣禮物增加貢獻值可進入排名，貢獻最多者和最後貢獻者獲得獎勵",
    span_title: "每週獎勵",
    rank_tips:
        "每週一0點結算榜單，根據榜單排名獲得對應獎勵，房間增加1點金幣流水=1點奇緣值，用戶每送出1金幣禮物=1點貢獻值；",
    prize_box1: "奇緣榜",
    prize_box2: "貢獻榜",
    prize_list1: "星空背景7天",
    prize_list2: "流量推薦30分鐘",
    prize_list3: "流量推薦15分鐘",
    prize_list4: "發燒友稱號7天",
    prize_list5: "發燒友進場秀7天",
    prize_list6: "發燒友進場秀7天",
    whichWeek0: "本週",
    whichWeek1: "上週",
    whichMainTab0: "奇緣榜",
    whichMainTab1: "貢獻榜",
    score: "貢獻值",
    score1: "奇緣值",
    rule_tips:
        "每個房間均可參與「小音奇緣」，玩法分為兩個階段，通過增加房間流水可累計奇緣值，達成進度後觸發「小音降臨」可獲得房間和用戶獎勵，並進入限時60分鐘的「小音祝福」階段，再次達成後將獲得更豐富的獎勵",
    ground1_title: "小音降臨",
    ground1_tips:
        "當前房間每增加1金幣流水=1點奇緣值，玩家每貢獻1點金幣流水=1點貢獻值，<i>房間累計達到10000點奇緣值</i>觸發「小音降臨」獎勵，並進入「小音祝福」階段，獎勵如下：",
    ground1_li1_title: "小音降臨",
    ground1_li1_tips: "房間稱號30分鐘",
    ground1_li2_title: "貢獻最多者",
    ground1_li2_tips: "飛碟音-奇緣禮物x5<br />小音奇緣-奇緣勛章1天",
    ground1_li3_title: "最後貢獻者",
    ground1_li3_tips: "小音奇緣-奇緣勛章1天",
    ground2_title: "小音祝福",
    ground2_tips:
        "「小音祝福」階段限時60分鐘，在限定時間內，當前房間每增加1金幣水流=1點奇緣值，玩家每貢獻1點金幣流水=1點貢獻值，<i>房間累計達到20000點奇緣值</i>觸發「小音祝福」獎勵，達成或超過時間均會回到「小音降臨」階段重新累計，獎勵如下：",
    ground2_li1_title: "熱門推薦",
    ground2_li1_tips: "流量曝光60分鐘",
    ground2_li2_title: "貢獻最多者",
    ground2_li2_tips: "音為有你-稀有禮物x1<br />飛船-稀有頭像框1天",
    ground2_li3_title: "最後貢獻者",
    ground2_li3_tips: "飛船-稀有頭像框1天",
    ground3_title: "幸運水晶球",
    ground3_tips:
        "每次達成「小音降臨」、「小音祝福」階段均觸發「幸運水晶球」出現，房間內的所有玩家均可進行占卜獲得獎勵，如下：",
    ground3_gifts1_title: "小音降臨階段",
    ground3_gifts2_title: "小音祝福階段",
    ground3_probability: "占卜概率(萬分制)",
    ground4_title: "奇緣榜單",
    ground4_tips:
        "每週一0點結算上週的奇緣榜單，根據上週的房間奇緣總值，用戶的貢獻總值排榜，前3名獲得獎勵，如下：",
    ground4_reward1_title: "奇緣榜",
    ground4_reward1_tips1: "星空背景7天<br />流量推薦卡30分鐘",
    ground4_reward1_tips2: "流量推薦卡15分鐘",
    ground4_reward2_title: "貢獻榜",
    ground4_reward2_tips1: "發燒友稱號7天<br />發燒友進場秀7天",
    ground4_reward2_tips2: "發燒友進場秀7天",
    rule_other_title: "其他說明",
    rule_other: [
        "通過玩法獲得的道具，具有一定的有效期，請及時使用；",
        "房間獲得的流量推薦卡僅限本週，可聯繫官方人員使用；",
        "禁止實施任何影響互動公平性的行為，或利用平台BUG等不正當手法參與玩法，一旦發現，平台有權取消道具發放，追回道具；",
        "本活動與蘋果公司無關，最終解釋權歸音覓所有。",
    ],
    share_title: "小音奇緣",
    share_desc: "",
};
