const lang = {
    // noAct: '活動未開始',
    // actEd: '活動已結束',
    ok: 'تحديد    ',
    rules: 'التفسير عن إقامة الحفلة',
    myAct: 'الحفلة لي    ',
    creatAct: 'تقديم الطلب لإقامة الحفلة    ',
    noActData: 'لا يوجد معطيات الآن! يرجي تقديم الطلب!    ',
    officialAct: 'النشاط الرسمي    ',
    firePeople: 'المنظم:    ',
    kRoom: 'رقم الغرفة:',
    date: 'وقت النشاط:',
    peopleTips: 'شخص في الحفلة الآن',
    // singUp: '報名',
    actDetil: 'تفاصيل النشاط    ',
    attention: 'متابعة    ',
    attention2: 'إلغاء المتابعة    ',
    rid: 'رقم الغرفة:',
    actTips: 'وصف النشاط    ',
    actGifts: 'جوائز النشاط    ',
    goRoom: 'يدخل الغرفة    ',
    // singUpTips1: '填寫個人簡介即可提交報名',
    // singUpTips2: '活動創辦者將會聯絡告知你報名結果，請耐心等待',
    // singUpTips3: '我在歡歌有2131位粉絲，很擅長唱臺語歌，最拿手的歌曲是周杰倫的【告白氣球】，很希望能入選作為你們活動的演唱嘉賓，把我的聲音唱給歡友們聽。（參考範例）',
    // singUpTipsCom: '提交報名',
    actBarTitle: 'مراجعة التقدم    ',
    actBarTips1: 'في انتظار المراجعة    ',
    actBarTips2: 'جار المراجعة    ',
    actBarTips3: 'فشل نتيجة المراجعة    ',
    actBarTips4: 'اجتازت المراجعة    ',
    actBarTips5: 'تقييم المراجعة:',
    actBarTips6: 'محتويات النشاط رائعة جدا، يلا اخبر أصدقائك لمتابعة النشاط!    ',
    actBarChang: 'تعديل النشاط    ',
    // singUpDetil: '報名詳情',
    // singUpNoData: '暫無報名，快去邀請好友吧~',
    // singUpMsg: '報名簡介',
    // ms: '私訊'
}
export default lang