// https://brushes8.com/zhong-wen-jian-ti-fan-ti-zhuan-huan
export default {
    title: 'cp任務及獎勵',

    envy_others: '羨煞旁人',
    current_cp_level: '當前CP等級',
    level_des: '甜蜜值：{0}，升級還需{1}',
    
    coming_soon: '敬請期待',
    daily_cp_task: '每天CP任務',
    daily_refresh: '每日0點刷新',

    task_des_1: '單人打卡%s%0甜蜜值+10%1,雙人打卡%s%0甜蜜值+100%1',
    task_des_2: '單人打卡%s%0甜蜜值+10%1,雙人打卡%s%0甜蜜值+100%1',
    task_des_3: '每對私訊%s%0甜蜜值+1%1',
    task_des_4: '在同一房間內每分鐘%s%0甜蜜值+1%1',
    task_des_5: '撥通一次語音通話',
    clock_in: '打卡',
    clock_in_succ: '打卡成功',

    cp_level: 'CP等級',
    cp_level_title_1: '1.怎麼提升CP等級？',
    cp_level_des_1: 'CP等級根據甜蜜值提升，CP等級對應甜蜜值的關係如下表',
    cp_level_title_2: '2.怎麼提升甜蜜值？',
    cp_level_des_2: '甜蜜值可通過互相送禮、購買新戒指、接受祝福禮物、完成CP任務提升。',
    cp_level_title_3: '3.等級提升後的獎勵怎麼獲取？',
    cp_level_des_3: '等級提升後如果有對應特效獎勵，將會自動生效；而有道具獎勵的話，將會自動發送到你的背包，並且會給你發小助手消息提示哦！',
    love_value: '甜蜜值',
    cp_table_title_1: '初入愛河',
    cp_table_title_2: '一往情深',
    cp_table_title_3: '情投意合',
    cp_table_title_4: '矢志不渝',
    cp_table_title_5: '海誓山盟',
    cp_table_title_6: '天荒地老',
    cp_table_value_1: '≥0',
    cp_table_value_2: '≥3300',
    cp_table_value_3: '≥7000',
    cp_table_value_4: '≥14500',
    cp_table_value_5: '≥30000',
    cp_table_value_6: '≥100000',

    cp_explain: 'CP說明',
    explain_title_1: '1.怎樣擁有自己的CP小窩？',
    explain_des_1: '當你和你心儀的對象成為CP後，即可擁有你們的CP小窩',
    explain_title_2: '2.甜蜜值有什麼作用？如何提升甜蜜值？',
    explain_des_2: '甜蜜值可以帶來CP關係升級解鎖新的CP關係特權；甜蜜值可通過互相送禮、購買新戒指、完成CP任務提升。',
    explain_title_3: '3.解除CP關係之後CP小窩之類的還在嗎？',
    explain_des_3: '解除CP關係後，你將暫時失去你們之間的CP小窩，但之後如果你們復合了CP關係（重新告白），將可繼承此前的CP專頁和對應的甜蜜值。（當然，解除CP關係後，你們的甜蜜值會停止成長）',
    explain_title_4: '4.更換戒指會有什麼效果？',
    explain_des_4: '成為CP後，更換戒指會用新的戒指替換舊的戒指，並獲取新戒指帶來的數值獎勵，同時也可以在戒指盒裡選擇自己喜歡的戒指。',
}