export default {
    //html/index.html
    title: "VỊT CƯNG CẠP CẠP",
    act_rule: "Thể lệ và thưởng",
    feed_record: "Lịch sử",
    user_duck: "Vịt cưng của %s",
    award_title_1: "Cối xay gió nh",
    award_title_2: "Bong bóng cầu vồng",
    award_title_3: "Nụ hôn tình yêu",
    award_title_4: "Lưu thủy hành vân(1 ngày)", //Vui vẻ (1 ngày)
    award_title_5: "Xe đua(7 ngày)", //Xe đua (7 ngày)
    award_title_6: "Đăng quang(3 ngày)",
    award_title_7: "Đàn vịt ngang qua(1 ngày)",
    award_title_8: "88 đậu",
    award_title_9: "25 xu",
    award_des_1: "",
    award_des_2: "Qùa động",
    award_des_3: "Qùa động",
    award_des_4: "Khung ảnh",
    award_des_5: "Xe",
    award_des_6: "Khung ảnh",
    award_des_7: "Xe",
    award_des: "Dùng xu mua thức ăn chăn vịt, có cơ hội nhận thưởng",
    duck_happy_value: "Số lần chăn",
    gift_title_1: "Qùa động Mèo \ncon (7 ngày)",
    gift_title_2: "Đàn vịt ngang\nqua(3 ngày)",
    gift_title_3: "Đăng quang\n(7 ngày)",
    my_coin: "Xu của tôi %s",
    notice: "[{0}]Nhận quà vịt cưng [{1}]",
    step_award_succ: "Cảm ơn chủ nhận đã nuôi, tặng chủ nhân %s",

    toast_1: "Tôi sẽ luôn bên chủ nhân ",
    toast_2: "Chủ nhân cho tôi ăn đúng giờ nhé ",
    toast_3: "Tôi muốn chủ nhân luôn bên tôi",
    toast_4: "Ngày mai lại tới thăm tôi nhé",
    toast_5: "Vịt bụng to, cạp cạp to",
    toast_6: "Điểm cạp cạp đạt đủ sẽ nhận một phần quà độc",
    toast_7: "Hi vọng mỗi ngày đều mang cho chủ nhân niềm vui",
    toast_8: "Vui vẻ là phải cạp cạp",
    toast_9: "Người tốt sẽ thường đến thăm vịt",
    toast_10: "Nói nhỏ với chủ nhân, có người đang yêu thầm chủ nhân đó",
    toast_11: "Người tốt sẽ thường cho vịt ăn",
    toast_12: "Cho vịt ăn no, vịt sẽ tặng quà cho chủ nhân",

    happy_value: "Điểm",
    first_dialog_des:
        "Chủ nhân, tôi là chú vịt vui vẻ, \n tôi có thể bên chủ nhân mỗi ngày chăn tôi, tôi sẽ tặng chủ  nhân một phần quà",
    award_dialog_des: "Cảm ơn chủ nhân cho tôi ăn \n Tăng %s điểm",
    car_day: "Xe (%s ngày)",
    frame_day: "Khung ảnh (%s ngày)",
    gift_day: "-Qùa động(%s ngày)",
    record: "Chăn vịt {1} lần, nhận {2}",
    time: "HH:MM dd/mm",
    bean: "%s đậu",
    coin: "%s xu",
    loading: "Đang tải",
    coming_soon: "Vui lòng chờ đợi",
    not_data: "Chưa có dữ liệu",
    use_coin_feed: "Sử dụng %s xu cho vịt ăn no",

    //rule
    act_time: "Thời gian %s",
    s_time: "HH:MM dd/mm/YYYY",
    e_time: "HH:MM:SS dd/mm",
    how_play: "1, Làm sao để chăn vịt",
    how_play_des_1:
        "Vịt cưng cạp cạp dễ thương nhất quả đất, mỗi ngày có thể chăn vịt cưng, nuôi vịt cưng, nói chuyện cùng vịt cưng, vịt cưng sẽ tặng bạn một phần quà nho nhỏ chúc bạn luôn vui vẻ đấy.",
    how_play_des_2:
        "Khi chăn vịt đạt số lần đã định, sẽ được nhận quà tương ứng",
    duck_gift: "2, Qùa vịt cưng",
    duck_gift_des_1: "Vịt cưng sẽ tặng bạn những món quà sau",
    duck_gift_des_2:
        "Qùa sự kiện có hiệu lực 7 ngày, sau khi hết hiệu lực sẽ không hiển thị nữa ",
    list_award: "3, Thưởng BXH vịt cưng",
    list_award_des_1:
        "Top 1: Huy chương thần tốc 10 ngày, xe đua 7 ngày, khung ảnh đăng quang 7 ngày",
    list_award_des_2:
        "Top 2: Huy chương thần tốc 7 ngày, xe đua 7 ngày, khung ảnh đăng quang 7 ngày",
    list_award_des_3:
        "Top 3: Huy chương thần tốc 7 ngày, xe đua 5 ngày, khung ảnh đăng quang 5 ngày",
    list_award_des_4: "Top 4-6: khung ảnh đăng quang 3 ngày",
    apple: "* Sự kiện không liên quan đến tập đoàn apple",
    explain: "Quyết định cuối cùng thuộc về alochat",
    rate_1: "50%",
    rate_2: "1%",
    rate_3: "1%",
    rate_4: "15%",
    rate_5: "0.001%",
    rate_6: "0.5%",
    rate_7: "0.5%",
    rate_8: "8.999%",
    rate_9: "23%"
};
