const lang = {
    noAct: 'Sự kiện chưa bắt đầu',
    actEd: 'Sự kiện đã kết thúc',
    rule: 'Về sự kiện',
    history: 'Lịch sử đổi',
    rule1: '1. Trong thời gian sự kiện mỗi ngày sẽ mở nội dung sự kiện khác nhau, không thể xem trước nội dung của ngày chưa mở.',
    rule2: '2. Phần thưởng của sự kiện chỉ được nhận trong ngày, quá hạn sẽ mất.',
    rule3: '3. Vui lòng đổi phần thưởng kịp thời trong thời gian sự kiện, sau khi sự kiện kết thúc sẽ không thể đổi.',
    rule4: '4.Túi quà thưởng đều có thời hạn 7 ngày.',
    task: 'Nhiệm vụ',
    convertibility: 'Đổi',
    loading: 'Đang tải...',
    noOpen: 'Chưa mở, vui lòng đợi!',
    loginTitle: 'Quà đăng nhập hôm nay',
    nowDayTitle: 'Nhiệm vụ hôm nay',
    receive: 'Nhận',
    dayTasksTitle: 'Nhiệm vụ hôm nay',
    converGiftTitle: 'Đổi quà',
    converNum: 'Mỗi ngày đổi <br/> tối đa X lần',
    converNum2: 'Mỗi ngày đổi <br/>  tối đa X lần',
    dayEd: 'Hôm nay đã đổi',
    singUp: 'Báo danh',
    ok: 'Xác nhận',
    noSingUp: 'Mời báo danh trước~',
    openBoxTime: 'Thời gian',
    gift: 'Phần thưởng',
    historyTitle: 'Lịch sử đổi',
    singUpSuc: 'Báo danh xong!',
    noSuc: 'Chưa xong',
    dayNoOpen: 'Chưa mở, vui lòng đợi!',
    noChpin: 'Không đủ mảnh!',
    noDayRev: 'Phần thưởng nhiệm vụ hôm nay chỉ được nhận trong ngày!',
    noData: "Chưa có lịch sử đổi"
}
export default lang