const lang = {
    noAct: '活動未開始',
    actEd: '活動已結束',
    rule: '活動說明',
    history: '兌換記錄',
    rule1: '1. 活動期間按天數開啟當日的活動內容，不可提前查看未開啟天數的內容',
    rule2: '2. 福利及任務的獎勵僅限當天領取，過期無效',
    rule3: '3. 兌換的獎品請在活動時間內及時兌換,過期後自動清零',
    task: '任務',
    convertibility: '兌換',
    loading: '加載中...',
    noOpen: '暫未開放，敬請期待！',
    loginTitle: '今日登陸福利',
    nowDayTitle: '今日任務',
    receive: '領取',
    dayTasksTitle: '今日任務',
    converGiftTitle: '獎品兌換',
    converNum: '每天最多兌換X個',
    converNum2: '每天最多兌換X個',
    dayEd: '今日已兌換',
    singUp: '報名參與',
    ok: '確定',
    // noSingUp: 'Mời báo danh trước~',
    openBoxTime: '時間',
    gift: '獎品',
    historyTitle: '兌換記錄',
    singUpSuc: '報名成功',
    noSuc: '未完成',
    dayNoOpen: '暫未開放，敬請期待！',
    noChpin: '你的碎片不足哦，快去獲取碎片吧！',
    noDayRev: '每日福利及任務的獎勵僅限當天領取！',
    noData: "暫無數據！"
}
export default lang
