export default {
    //html/index.html
    title: "花車巡遊會",
    floowScore: "花神值",
    fanList: "粉絲守護團>",
    ruleTips: "規則獎勵",
    noUser: "虛位以待",
    type_tab1: "花神榜",
    type_tab2: "人氣榜",
    tab1: "日榜",
    tab2: "總榜",
    loading: "加載中...",
    noPeople: "暫無數據",
    rank_day: "天",
    rank_hour: "時",
    rank_min: "分",
    rank_second: "秒",
    noAct: "活動未開始",
    actEd: "活動已結束",
    taskHeader_tab1: "任務",
    taskHeader_tab2: "人氣值",
    taskHeader_tab3: "分數上限",
    taskHeader_tab4: "進度",
    taskScoreTips: "1人=%s分",
    noMax: "無上限",
    over: "已達成",
    todayScore: "今日人氣值:",
    userPup: "的粉絲守護團",
    user_rank: "排名",
    user_nick: "用戶",
    user_score: "貢獻花神值",
    userTips:
        "*貢獻花神值為粉絲對同一名主播縮貢獻的花神值總和，榜單顯示前20名粉絲",
    user_score_people: "貢獻人氣值",
    userTips_people::
        "*貢獻人氣值為粉絲對同一名主播縮貢獻的人氣值總和，榜單顯示前20名粉絲",
    goUser: "查看他的個人資料頁"
};
