export default {
    //html/index.html
    title: "驚喜盲盒",
    act_rule: "規則",
    record: "盲盒紀錄",
    total_collection: "查看我的總收藏 >>",
    get_frame: "當收集到7款，\n可獲得星夢無痕頭像框*7天",
    collection_num: "已收集到%s款櫻花限定禮物",
    series: "櫻花系列",
    select: "選它",
    friend_des: "雙方相互追蹤才是好友喔",
    give_friend: "贈送給：%s",
    cost_coin_des: "已選擇N個盲盒，需要花費%s金幣",
    give_succ_des: "贈送成功～ \n記得要提醒玩家打開盲盒喔",
    friend_give_box: "有好友送你盲盒喔",
    my_collection_des_1: "已收集到{0}款【{1}】盲盒禮物",
    my_collection_des_2: "已收集滿{0}套【{1}】盲盒禮物",
    hidn_num: "隱藏款剩餘{1}個",
    not_enough_coin: "你的金幣不足哦~",
    purchase_succ: "購買成功",
    rare: "稀有",
    hide: "隱藏",
    not_friend: "快去認識新朋友吧",
    not_data: "暫無數據",
    loading: "加載中",
    coll_gift_num: "已收集%s款",
    not_coll: "暫無收藏",
    see_ta_coll: "查看收藏",
    invite: "邀請開盒",
    invited: "已邀請",
    friend_coll_title: "【%s】的收藏",
    friend_coll_des: "歡迎來看我的盲盒收藏，我已經收集了%s款盲盒啦！",
    purchase_num_box: "購買了%s個盲盒",
    record_time: "mm月dd日 HH:MM",
    purchase_num_give: "購買了{0}個盲盒送給玩家\n【{1}】",
    opened: "已拆開",
    not_open: "未拆開",
    not_open_title: "【{0}】送出{1}個盲盒，仍有{2}個未拆開",
    open: "拆開",
    open_title: "拆開【{0}】\n 贈送{1}個盲盒",
    store_value: "收藏值",
    rank_item_des_1: "已收集%s套",
    rank_item_des_2: "已收集%s款",
    notice_des_1: "恭喜{0}獲得隱藏款【{1}】",
    notice_des_2: "恭喜{0}獲得稀有款【{1}】",
    notice_des_3: "恭喜{0}集齊{1}套盲盒",
    act_ended: "活動已結束",
    this_issue_list: "本期收藏家榜",
    total_issue_list: "總收藏家榜",
    hidn_gift: "隱藏款",

    //rule
    act_time: "活動時間：%s",
    s_time: "YYYY/mm/dd HH:MM",
    e_time: "mm/dd HH:MM:SS",
    rule_title_1: "購買盲盒",
    purchase_box_des:
        "玩家在盲盒的自動售賣機中，可以一次性購買1個或者9個盲盒，每個盲盒單價100金幣\n送自己：送給自己的盲盒在打開之後，盲盒抽中的禮物會存放在自己的背包中\n送好友：送給好友的盲盒，即由好友在活動頁中的開盲盒，並獲得背包禮物，存放在好友的背包中\n盲盒所得的背包禮物有效期均為7天",
    rule_title_2: "盲盒概率",
    rule_title_3: "榜單",
    rule_rank_des:
        "榜單按照玩家所獲得的收藏值從高到低進行排名，若收藏值一樣，先達到的玩家優先\n總榜顯示前50名玩家的收藏值",
    rule_title_4: "注意事項",
    matter_des:
        "1、活動中，若發現玩家用不正當手段參與活動，小音有權在不實現通知的情況下按照情節嚴重對玩家、違規者取消上榜資格、封禁賬號、回收該玩家所有獎勵等處罰，包括但不限於：活動期間對參與活動的玩家進行惡意攻擊、造謠、影射\n2、活動中獲得的背包禮物有效期均為7天\n3、若收到盲盒的玩家在活動結束後都沒有主動打開盲盒，將由系統自動打開盲盒並發放到玩家的背包中\n4、每位玩家僅可獲得一次本活動頭像框獎勵\n5、本活動與蘋果公司無關",
    explain: "*活動最終解釋權歸活動主辦方所有"
};
