const lang = {
    noAct: 'Sự kiện chưa bắt đầu',
    actEd: 'Sự kiện đã kết thúc',
    ok: 'Biết rồi',
    dTips1: 'Đang là thời gian có thể thả lọ',
    dayNum: 'Số lần nhặt hôm nay:',
    gNumTips: 'Đã nhặt X lọ ',
    gANumTips: '(có X lọ cao cấp)',
    openBottle: 'Mở lọ',
    dTime: 'Chưa đến lúc thả lọ, thời gian thả lọ từ X',
    gTime: 'Chưa đến thời gian nhặt lọ, thời gian nhặt lọ là X',
    noPlayer: 'Chưa tải hết tài nguyên, mời thử lại~',
    numOver: 'Số lần nhặt lọ đã hết~',
    me: 'Của tôi',
    firend: 'Bạn bè',
    noData: 'Chưa có dữ liệu',
    change: 'Chọn',
    loading: 'Đang tải...',
    noFriend: 'Chưa có bạn bè, hãy thêm nhé!',
    near: 'Bài hát mới:',
    lookWork: 'Xem bài hát',
    dSucess: 'Đã thả lọ',
    dSongTips: 'Bài hát được thả sẽ nhận lượt nghe và quan tâm~ Số người được thả càng nhiều, lượt nghe càng nhiều, bài hát chất lượng sẽ được nhiều lượt tiếp cận hơn~',
    again: 'Chọn lại',
    freeDb: 'Thả miễn phí',
    bayDb: 'Thả lọ đặc biệt',
    freeOver: 'Số lần miễn phí hôm nay đã hết',
    questTips: 'Mỗi người mỗi ngày lần đầu thả được miễn phí, xác nhận thả bài hát này?',
    qureyD: 'Xác nhận',
    dNum: 'Số người đề cử',
    coins: 'Xu:',
    coios2: 'Xu',
    bean: 'đậu',
    ok2: 'Biết rồi',
    cancel: 'Huỷ',
    goStored: 'Nạp ngay',
    songError: 'Tải nhạc thất bại, mời thử lại sau',

}
export default lang