const Lang = {
    MainVenue: '主會場',
    Pack: '我的背包',
    Rules: '獎勵&規則',
    ActNot: '活動未開始',
    ActEnd: '活動已結束',
    SingUp: '立即報名',
    Daily_b: '當前可用遊戲幣：',
    Score: '分數：',
    PlayValue: '玩樂值：',
    Determine: '我知道啦',
    GradeGift: '等級獎勵',
    Receive: '領取',
    Received: '已領取',
    TotalScore: '當局分數',
    DownTime: '倒計時',
    CombatantNumber: '連擊數',
    GameB: '盛典幣：',
    GameB2: '盛典幣',
    duce: '進度',
    StartGame: '開始遊戲',
    OneGameB: '20遊戲幣/次',
    mouseTips1: '打擊紫色地鼠加分，連擊分數更高',
    mouseTips2: '打擊綠色地鼠減分',
    noCoinsTips1: '您的遊戲幣餘額不足，無法開始遊戲',
    noCoinsTips2: '快去賺取遊戲幣吧！',
    noCoinsTips3: '您的遊戲幣餘額不足，無法兌換',
    noCoinsTips4: '您的遊戲幣餘額不足，無法抽獎',
    noCointTitle: '無法抽獎',
    NowScore: '本局獲得分數:',
    AchieveLv: '達到等級:',
    Again: '再來一局',
    upgraded: '抱歉，您的操作系統版本較低，不支持此遊戲請先升級操作系統哦！',
    NoSingUp: '未報名無法參與活動，請先報名哦',
    upScoreIng: '分數正在上報,請稍等~',
    ticketB: '·20遊戲幣/張 ·有效期1天',
    getTicketTips: '  每人每天僅限兌換1張同個活動選票</br>選票兌換後可在我的背包查看',
    exchang: '兌換',
    exchanged: '已兌換',
    NogetTicket: '該活動已結束</br>無法兌換該選票唷~',
    NogetTicket2: '活動未開始</br>請在有效兌換時間兌換該選票唷~',
    tabs1: '歡樂打地鼠',
    tabs2: '幸運大轉盤',
    tabs3: '年度選票兌換',
    bottomTabs1: '賺取遊戲幣',
    bottomTabs2: '歡樂地鼠榜',
    bottomTabs3: '頭號玩家榜',
    rankTips: '根據歡樂打地鼠項目獲得的分數排名',
    rankTips2: '玩樂值=使用的遊戲幣數量',
    Loading: '加載中...',
    deng: '敬請期待！',
    noPeople: '目前暫無歌友上榜',
    wait: ' 虛位以待，等你來哦！',
    Invitation: '邀請好友加油',
    ComeOn: '為好友加油',
    dayTask: '每日任務',
    reached: '已達成',
    lookWhole: '查看全部',
    nowTis: '當前階段',
    numB1: '20遊戲幣',
    numB2: '100遊戲幣',
    fiveTips: '恭喜您連抽5次獲得以下獎品',
    fiveTips2: '獎品已派發到您的賬戶上，請注意查收！',
}
export default Lang