const lang = {
    actState1: 'Sự kiện chưa bắt đầu',
    actState2: 'Sự kiện đã kết thúc',
    rules: 'Thể lệ&Thưởng>',
    mainVuev: 'Ngôi Sao Của Năm>',
    getTicket: 'Nhận phiếu bầu>',
    singUp: 'Báo danh',
    essence: 'Cốt cán',
    familyScore: 'Điểm gia tộc',
    familyScore2: 'Điểm Vinh Dự',
    familyTotalScore: 'Tổng điểm',
    coinsScore: 'Mị lực quà xu tặng',
    joinFamilyTips: 'Mời vào gia tộc trước đã',
    join: 'Nhấn vào',
    joinSuc: 'Chúc mừng bạn đã báo danh!',
    joinWait: 'Các tộc trưởng đang báo danh, đừng chậm trễ nhé~',
    joinNoF: 'Chỉ tộc trưởng, tộc phó được báo danh,Mau thông báo cho họ nhé~~',
    quMsg: 'Nhắn tin',
    query: 'Xác nhận',
    wait: '- Vui lòng đợi -',
    actIng: '- Bảng Vàng Gia Tộc đang diễn ra -',
    acted: '- Bảng Vàng Gia Tộc đã kết thúc -',
    day: 'ngày',
    houer: 'giờ',
    minute: 'phút',
    second: 'giây',
    familySo: 'Mị lực xu gia tộc nhận:',
    boxWards: 'Rương gồm quà sau',
    carveUped: 'Đã chia',
    carveUpNo: 'Hôm nay đã chia tối đa, sau 0h chia tiếp',
    carveUpTody: 'Mỗi ngày được mở tối đa 2 rương, 0h sáng hôm sau xoá hết rương còn lại',
    carveUpNoOpen: 'Mị lực xu chưa đạt điều kiện mở rương',
    // carveUpday2: '金幣魅力值已达到明日开启',
    tab1: 'BXH Gia Tộc',
    tab2: 'Cốt cán gia tộc',
    noData: 'Chưa ai xếp hạng',
    familyPoepleNum: 'Thành viên:',
    familyCardScore: 'Điểm gia tộc:',
    familyCardScore2: 'Điểm vinh dự:',
    familyCardRank: 'Hạng mị lực 2019:',
    familyCardAdd: 'Tăng điểm 2019:',
    familyCardAdd2: 'Tăng điểm cốt cán:',
    familyCardTotaScore: 'Tổng điểm:',
    rank1Tips: 'Điểm gia tộc = mị lực toàn bộ thành viên gia tộc nhận sau khi báo danh (bài hát + phòng Kara) * (1 + phần trăm tăng thêm) và mị lực từ phiếu bầu tặng cho gia tộc được tính thành điểm vinh dự, phiếu bầu được đổi từ cắc, tối đa 5000 mị lực quà đậu.',
    rank2Tips: 'Cốt cán gia tộc là top 3 thành viên nhận mị lực xu đạt 30k,Mỗi cốt cán tăng 1% điểm vinh dự của gia tộc, tối đa 3%'
}
export default lang