export default {
    alochat_tips: "Tạm thời không thể tặng hộp quà cho bạn bè nhé",

    //html/index.html
    title: "Hộp Quà Kỳ Diệu",
    act_rule: "Quy tắc",
    record: "Lịch sử",
    total_collection: "Xem thu thập của thôi",
    get_frame: "Khi sưu tầm đủ 7 loaij,\n có thể nhận khung Nấm 7 ngày",
    collection_num: "Đã sưu tầm được %s quà trong sự kiện hưởng thụ cuộc sống",
    series: "Các loại anh đào",
    select: "Chọn",
    friend_des: "Cùng nhau cố gắng mới là bạn tốt",
    give_friend: "Tặng cho:%s",
    cost_coin_des: "Đã chọn N hộp quà, cần dùng %s Xu",
    give_succ_des: "Đã tặng \nNhớ nhắc họ mở quà nhé",
    friend_give_box: "Bạn được tặng hộp quà",
    my_collection_des_1: "Đã nhận được {0} loại [{1}]Hộp quà kỳ diệu",
    my_collection_des_2: "Đã thu thập đủ {0} bộ [{1}]Hộp quà kỳ diệu",
    hidn_num: "Qùa bí ẩn còn {1} chiếc",
    not_enough_coin: "Xu không đủ",
    purchase_succ: "Đã mua",
    rare: "Hiếm",
    hide: "Ẩn",
    not_friend: "Mau đi kêu gọi bạn mới",
    loading: "Đang tải",
    coming_soon: "Vui lòng chờ đợi",
    not_data: "Chưa có dữ liệu",
    coll_gift_num: "Đã nhận %s loại",
    not_coll: "Chưa có bộ sưu tập",
    see_ta_coll: "Xem cất giữ",
    invite: "Mời mở hộp",
    invited: "Đã mời",
    friend_coll_title: "Sưu tập của [%s]",
    friend_coll_des:
        "Mời bạn tới xem quà sưu tập của hộp quà kỳ diệu fucar tôi, tôi đã thu thập được %s loại quà bí mật！",
    purchase_num_box: "Đã mua %s hộp quà vào",
    record_time: "HH:MM dd/mm",
    purchase_num_give: "Đã mua {0} hộp quà tặng cho người chơi\n[{1}]",
    opened: "Đã mở",
    not_open: "Chưa mở",
    not_open_title: "[{0}]tặng {1} hộp quà, có {2} hộp chưa mở",
    open: "Mở",
    open_title: "Mở[{0}]\n tặng {1} hộp quà",
    store_value: "Điểm thu thập",
    rank_item_des_1: "Đã thu thập %s bộ",
    rank_item_des_2: "Đã thu thập %s món",
    notice_des_1: "Chúc mừng [{0}] nhận món quà ẩn [{1}]",
    notice_des_2: "Chúc mừng [{0}] nhận món quà hiếm [{1}]",
    notice_des_3: "Chúc mừng [{0}] thu thập được {1} bộ hộp quà",
    act_ended: "Event đã kết thúc",
    this_issue_list: "BXH kỳ này",
    total_issue_list: "BXH Tổng",
    hidn_gift: "Loại sưu tầm",

    //rule
    act_time: "Thời gian:%s",
    s_time: "HH:MM dd/mm/YYYY",
    e_time: "HH:MM:SS dd/mm",
    rule_title_1: "Mua hộp quà",
    purchase_box_des:
        "Người chơi có thể mua 1 hoặc 9 hộp quà tại máy bán hộp quà tự động, mỗi hộp quà giá 50 Xu\nTặng chính mình: Hộp quà tự tặng chính mình sau khi được mở, quà sẽ lưu trong túi của bản thân\nTặng bạn bè: Hộp quà tặng cho bạn bè, được bạn bè mở tại giao diện sự kiện và quà nhận được lưu trong túi của bạn bè\nQuà nhận từ hộp quà có thời hạn 7 ngày",
    rule_title_2: "Tỉ lệ hộp quà",
    rule_title_3: "Bảng Xếp Hạng",
    rule_rank_des:
        "Xếp hạng dựa vào điểm thu thập từ cao đến thấp, khi điểm bằng nhau thì người đạt trước sẽ được xếp cao hơn\nBảng xếp hạng hiển thị tên người chơi trong Top 50 điểm thu thập ",
    rule_title_4: "Lưu ý",
    matter_des:
        "1. Trong sự kiện, khi phát hiện người chơi gian lận, chúng tôi sẽ hủy bỏ tư cách xếp hạng của người vi phạm mà không cần thông báo, đồng thời sẽ khóa tài khoản và thu hồi các phần thưởng của người chơi, bao gồm và không giới hạn: khi tham gia sự kiện có lời lẻ xúc phạm đến người tham gia khác\n2. Quà tặng nhận được trong sự kiện sẽ có thời hạn trong 7 ngày\n3. Người chơi nhận được hộp quà kỳ diệu, khi sự kiện kết thúc nếu không chủ động mở quà, hệ thống sẽ tự động mở ra và chuyển quà đến túi của người chơi\n4. Mỗi người chơi chỉ có thể nhận 1 phần quà khung ảnh của sự kiện\n5. Sự kiện không liên quan đến công ty Apple",
    explain: "Quyền quyết định cuối cùng thuộc về BQT",
    rate:
        "cô bưu tá-Điểm thu thập750-25%<br/>cô trồng lúa-Điểm thu thập750-25%<br/>cô nấu ăn-Điểm thu thập800-19.75%<br/>cô trồng hoa quà-Điểm thu thập870-13%<br/>cô nuôi gia súc-Điểm thu thập920-8%<br/>cô dệt áo-Điểm thu thập920-8%<br/>cô giỏi học-Điểm thu thập990-1%<br/>cô dự đoán-Điểm thu thập1500-0.25%"
};
