const lang = {
    actState1: '活動未開始',
    actState2: '活動已結束',
    rules: '規則&獎勵>',
    mainVuev: '年度之星會場>',
    getTicket: '獲取榮耀票>',
    singUp: '點擊報名',
    essence: '菁英',
    familyScore: '家族積分值',
    familyScore2: '榮耀票值',
    familyTotalScore: '總值',
    coinsScore: '金幣收禮魅力值',
    joinFamilyTips: '請先加入一個家族',
    join: '去加入',
    joinSuc: '恭喜您報名成功！',
    joinWait: '族長們正在前來報名的路上，</br>請勿著急哦~',
    joinNoF: '本活動僅限家族長、副族長點報名</br>快去告知他們吧~',
    quMsg: '確認私訊',
    query: '確認',
    wait: '- 敬請期待 -',
    actIng: '- 金牌家族荣耀赛进行中 -',
    acted: '- 金牌家族荣耀赛已結束 -',
    day: '天',
    houer: '時',
    minute: '分',
    second: '秒',
    familySo: '家族收禮金幣魅力值:',
    boxWards: '寶箱包含以下禮物',
    carveUped: '已瓜分',
    carveUpNo: '今日已達瓜分上限，零點刷新後可瓜分',
    carveUpTody: '每日開啟寶箱限2個,零點刷新',
    carveUpNoOpen: '金幣魅力值未滿足寶箱開啟條件',
    // carveUpday2: '金幣魅力值已达到明日开启',
    tab1: '金牌家族榜',
    tab2: '家族菁英榜',
    noData: '暫無歌友上榜',
    familyPoepleNum: '家族成員:',
    familyCardScore: '家族積分:',
    familyCardScore2: '家族榮耀值:',
    familyCardRank: '2019魅力排名:',
    familyCardAdd: '2019年度加成:',
    familyCardAdd2: '菁英加成:',
    familyCardTotaScore: '總榮耀值:'
}
export default lang