const msgArr = {
    1: {
        title: 'Thể lệ vòng loại',
        msg: "1. Xếp hạng theo điểm sôi nổi, tức điểm mị lực nhận quà Xu từ bài hát + phòng kara và chủ phòng trong thời gian sự kiện;<br/>2. Nếu điểm sôi nổi bằng nhau, thì người đạt điểm trước sẽ được xếp cao hơn;<br/>3. Sau khi vòng loại kết thúc, top 400 sẽ được vào vòng tiếp theo;<br/>4. Top 5 BXH vòng này sẽ nhận được giải thưởng đặc biệt của vòng này;<br/>5. Thời gian vòng này: 18:00 14/12/2020 - 23:59 16/12/2020",
        msg2: 'Bài hát = điểm mị lực nhận quà Xu từ tất cả bài hát công khai của thí sinh trong thời hạn vòng này.<br/>Phòng kara = điểm mị lực nhận quà Xu từ phòng kara của thí sinh khi lên mic trong thời hạn vòng này. <br/>Chủ phòng (4%) = điểm mị lực nhận được từ phòng kara của thí sinh khi người dùng khác nhận được quà Xu khi lên mic*4%<br/><span>Sau khi kết thúc mỗi vòng, dữ liệu BXH sẽ được xóa hết. </span> '
    },
    2: {
        title: 'Thể lệ 1 VS 1:',
        msg: "1.Hệ thống sẽ ghép cặp đấu 1 VS 1 ngẫu nhiên cho bạn;<br/>2.Cặp đấu có tổng điểm sôi nổi cao hơn thì sẽ được xếp cao hơn; Nếu điểm sôi nổi bằng nhau thì cặp đấu đạt điểm trước sẽ được xếp cao hon;<br/>Điểm sôi nổi sẽ được tính bằng điểm mị lực nhận quà Xu từ bài hát+phòng kara và chủ phòng trong thời hạn 1 VS 1. Thí sinh có điểm sôi nổi cao hơn trong mỗi cặp đấu sẽ được vào vòng tiếp theo. Vòng này sẽ có 200 thí sinh có cơ hội vào vòng tiếp theo. <br/>Nếu gặp phải trường hợp bỏ thi đấu thì đối thủ sẽ tự động thắng và vào vòng tiếp theo;<br/>Nếu gặp phải trường hợp 2 bên số điểm như nhau (hòa) thì sẽ được coi là 2 bên đều bị loại, và không thể vào vòng tiép theo;<br/>Thí sinh vào vòng tiếp theo trong top 5 cặp đấu của BXH vòng này sẽ nhận được giải thưởng đặc biệt của vòng này;<br/>7. Thời gian vòng này: 00:05 17/12/2020 - 23:59 19/12/2020",
        msg2: 'Bài hát = điểm mị lực nhận quà Xu từ tất cả bài hát công khai của thí sinh trong thời hạn vòng này.<br/>Phòng kara = điểm mị lực nhận quà Xu từ phòng kara của thí sinh khi lên mic trong thời hạn vòng này. <br/>Chủ phòng (4%) = điểm mị lực nhận được từ phòng kara của thí sinh khi người dùng khác nhận được quà Xu khi lên mic*4%<br/><span> Sau khi kết thúc mỗi vòng, dữ liệu BXH sẽ được xóa hết. </span> '
    },
    3: {
        title: 'Thể lệ đấu đội: ',
        msg: " Xếp hạng theo điểm sôi nổi của top 200 thí sinh vòng trước, và sẽ được chia thành 4 đội ngẫu nhiên;<br/>2.Xếp hạng đội: xếp hạng theo tổng điểm sôi nổi của các thành viên trong đội tại vòng này. Đội có tổng điểm sôi nổi cao hơn sẽ được xếp cao hơn;<br/>3. Xếp hạng cá nhân: điểm sôi nổi sẽ được tính bằng điểm mị lực nhận quà Xu từ bài hát+phòng kara+chủ phòng của mỗi thành viên trong nhóm, tổng điểm cao hơn thì sẽ được xếp cao hơn. Xếp hạng cao hơn sẽ được vào vòng tiếp theo; Nếu điểm sôi nổi bằng nhau thì thí sinh đạt điểm trước sẽ được xếp cao hon;<br/>4. Đội hạng 1 vòng này sẽ có 9 thí sinh được vào vòng tiếp theo. Đội hạng nhì sẽ có 8 thí sinh được vào vòng tiếp theo. Đội hạng 3 sẽ có 7 thí sinh được vào vòng tiếp theo. Đội hạng 4 sẽ có 6 thí sinh được vào vòng tiếp theo. Vòng này sẽ có 30 thí sinh được vào vòng tiếp theo;<br/>5. Thành viên đứng hạng 1 trong mỗi đội tại vòng này sẽ nhận được giải thưởng đặc biệt của vòng này;<br/>6. Thời gian vòng này: 00:05 20/12/2020 - 23:59 22/12/2020",
        msg2: 'Bài hát = điểm mị lực nhận quà Xu từ tất cả bài hát công khai của thí sinh trong thời hạn vòng này.<br/>Phòng kara = điểm mị lực nhận quà Xu từ phòng kara của thí sinh khi lên mic trong thời hạn vòng này. <br/>Chủ phòng (4%) = điểm mị lực nhận được từ phòng kara của thí sinh khi người dùng khác nhận được quà Xu khi lên mic*4%<br/><span> Sau khi kết thúc mỗi vòng, dữ liệu BXH sẽ được xóa hết. </span> '
    },
    4: {
        title: 'Thể lệ vòng chung kết:',
        msg: "1. 30 thí sinh vòng này sẽ live trong phòng kara Official chỉ định vào 20:00 25/12；<br/>2. Điểm Đại Diện của thí sinh sẽ được tính bằng điểm mị lực nhận quà Xu từ bài hát+phòng kara (kể cả phòng kara chung kết). Trên BXH vòng này, thí sinh nếu thứ tự càng cao thì sẽ được quyền ưu tiên xếp mic. BXH sẽ căn cứ vào điểm Đại Diện trước 00:00 24/12 của thí sinh vòng này. Trước khi bắt đầu live, ban tổ chức sẽ liên hệ thí sinh để xác định những việc liên quan như lịch trình cụ thể, v. v;<br/>3. Thí sinh sẽ nhận thêm 10% điểm mị lực khi lên mic vào 20:00 - 23:00 25/12 trong phòng kara chung kết;<br/>4. Tổng thành tích của thí sinh sẽ được tính bằng điểm Đại Diện (kể cả trong phòng kara chung kết) tại vòng này. Top 11 sẽ có cơ hội trở thành Gương Mặt Đại Diện và nhận được giải thưởng tương ứng;<br/>5. Thời gian vòng này: 00:05 23/12/2020 - 23:00 25/12/2020",
        msg2: 'Bài hát = điểm mị lực nhận quà Xu từ tất cả tác phẩm công khai của thí sinh trong thời hạn vòng này. <br/>Phòng kara thường = điểm mị lực nhận quà Xu từ phòng kara khác (ngoài phòng kara chung kết ra) của thí sinh khi lên mic trong thời hạn vòng này. <br/>Phòng kara chung kết = điểm mị lực nhận quà Xu từ phòng kara Official chỉ định khi thí sinh lên mic trong 20:00-23:00 25/12 (cộng 10%).  '
    }
}
export default msgArr