const lang = {
    rule: 'Thể lệ',
    history: 'Lịch sử nhận',
    actNo: 'Sự kiện chưa bắt đầu！',
    acted: 'Sự kiện đã kết thúc！',
    singUp: 'Báo danh',
    todayNum: 'Số lần lật bài hôm nay:',
    used: 'Đã dùng',
    ci: 'lần',
    todayScore: 'Năng lượng hôm nay',
    changTask: 'Chọn nhiệm vụ Thần Bài hoặc Vua Bài',
    changOne2: 'Chọn 1 trong 2 chế độ (trong thời gian sự kiện không thể đổi)',
    bigTask: 'Chế độ Thần Bài',
    mTask: 'Chế độ Vua Bài',
    taskOne: '1000 năng lượng/lần lật bài',
    changBig: 'Chọn chế độ Đại Vương',
    changMid: 'Chọn chế độ Vua Bài',
    noNum: 'Đã lật hết số bài hôm nay',
    oneNum: 'Lật 1',
    prize: 'Chúc mừng nhận',
    twoPrize: 'Dùng Thẻ x2 nhận',
    prizeTips: 'Phần thưởng gửi tức thì vào tài khoản',
    query: 'Xác nhận',
    noScore: 'Điểm năng lượng của bạn không đủ, mau đi làm nhiệm vụ đi',
    goSingUp: 'Mời báo danh để tham gia Đại Chiến Lật Bài',
    goSingUp2: 'Mau tới báo danh tham gia Đại Chiến Lật Bài nào!',
    excludeTips: 'Bỏ loại thẻ đã nhận, lần lật bài sau sẽ không nhận loại thẻ này',
    exclude: 'Loại bỏ',
    excludeUse: 'Huỷ dùng',
    userType: 'Đã loại bỏ',
    nextTips: 'Lần lật sau sẽ không nhận loại này',
    changOne: 'Loại bỏ 1 loại bài đã nhận',
    price: 'Giá: 300 đậu',
    price2: 'Giá: 50 đậu',
    usedCard: 'Đã dùng',
    hasCard: 'Đã có',
    noHas: 'Chưa có',
    use: 'Dùng',
    buy: 'Mua',
    nextDouble: 'Lần lật bài sau nhân đôi thưởng',
    rexUse: 'Huỷ dùng',
    buyCardTitle1: 'Mua Loại bỏ bài',
    buyCardTitle2: 'Mua thẻ nhân đôi',
    buyCardTips1: 'Loại bỏ loại bài đã nhận',
    noCards: 'Bài hôm nay đã lật xong! Mời mai lại đến nhé~',
    hfOne: 'Bạn phải lật một bài trước nhé~ Mau đi lật bài nào!',
    gx: 'Chúc mừng',
    get: 'nhận',
    taskScore: 'Năng lượng',
    taskBar: 'Tiến độ',
    suc: 'Xong',
    taskTaskEd: 'Đã chọn chế độ Vua Bài',
    taskTaskTips: 'Trong ngày hoàn thành toàn bộ nhiệm vụ Vua Bài nhận xe Audi 7 ngày (tự động gửi thưởng)',
    taskTaskEd2: 'Đã chọn chế độ Thần Bài',
    taskTaskTips2: 'Trong ngày hoàn thành toàn bộ nhiệm vụ Thần Bài nhận xe Ferrari 7 ngày (tự động gửi thưởng)',
    openTime: 'Thời gian lật',
    openGet: 'Quà nhận',
    noData: 'Chưa có số liệu',
    qux: 'Huỷ'
}
export default lang