export default {
    //html/index.html
    title: "花車巡遊會",
    floowScore: "花神值",
    peopleScore: "熱度值",
    fanList: "粉絲守護團>",
    ruleTips: "規則獎勵",
    noUser: "虛位以待",
    type_tab1: "花神榜",
    type_tab2: "熱度榜",
    tab1: "日榜",
    tab2: "總榜",
    loading: "加載中...",
    noPeople: "收集指定禮可登上花神榜，完成熱度任務可登上熱度榜哦",
    rank_day: "天",
    rank_hour: "時",
    rank_min: "分",
    rank_second: "秒",
    noAct: "活動未開始",
    actEd: "活動已結束",
    taskHeader_tab1: "任務",
    taskHeader_tab2: "熱度",
    taskHeader_tab3: "熱度上限",
    taskHeader_tab4: "進度",
    taskScoreTips: "1人=%s分",
    noMax: "無上限",
    over: "已達成",
    todayScore: "今日熱度:",
    userPup: "的粉絲守護團",
    user_rank: "排名",
    user_nick: "用戶",
    user_score: "貢獻花神值",
    user_score2: "貢獻熱度值",
    userTips:
        "*貢獻花神值為粉絲對同一名主播所貢獻的花神值總和，榜單顯示前20名粉絲",
    user_score_people: "貢獻熱度值",
    userTips_people:
        "*貢獻熱度為粉絲對同一名主播所貢獻的熱度總和，榜單顯示前20名粉絲",
    goUser: "查看他的個人資料頁"
};
