const lang = {
    // noAct: '活動未開始',
    // actEd: '活動已結束',
    ok: 'Ya',
    rules: 'Panduan pesta ',
    myAct: 'Pesta saya',
    creatAct: 'Mendaftar lakukan pesta',
    noActData: 'Belum ada data! Ayo mendaftar ya ！',
    officialAct: 'Acara resmi',
    firePeople: 'Penyelenggara:',
    kRoom: 'Kamar karaoke acara:',
    date: 'Waktu Acara:',
    peopleTips: 'org sedang berpesta',
    singUp: 'mendaftar',
    actDetil: 'Detail acara ',
    attention: 'Ikuti',
    attention2: 'Bata',
    rid: 'Nomor kamar:',
    actTips: 'Deskripsi acara',
    actGifts: 'Hadiah acara',
    goRoom: 'Masuk',
    singUpTips1: 'Tulis profil pribadi akan bisa kirim pendaftaran',
    singUpTips2: 'Pendiri acara akan kabari anda hasil pendaftaran,silakan tunggu ya',
    singUpTips3: 'Aku di Wekara ada fansnya 2131, aku pandai menyanyi, sangat pandai lagu {Dekat di hati}, aku harap bisa menjadi tamu yg acara kalian.(contoh)',
    singUpTipsCom: 'Kirim Pendaftaran',
    actBarTitle: 'Kemajuaan tinjau',
    actBarTips1: 'Ditunggu ditinjau',
    actBarTips2: 'Sedang ditinjau',
    actBarTips3: 'Pemeriksaan gagal',
    actBarTips4: 'Tinjau lulus',
    actBarTips5: 'Tinjau komentar: ',
    actBarTips6: ' Program acara bagus, ayo cepat panggil teman2 ikuti acara!! ',
    actBarChang: 'Ubah program',
    singUpDetil: 'Detail',
    singUpNoData: ' belum mendaftar,undangan teman2 dulu!',
    singUpMsg: 'Pendaftaran pendahuluan',
    ms: 'Kirim pesan',
    rank: 'Peringkat'
}
export default lang