const lang = {
    noAct: 'Sự kiện chưa bắt đầu',
    actEd: 'Sự kiện đã kết thúc',
    ok: 'Biết rồi',
    rules: 'Thể lệ&Thưởng',
    history: 'Lịch sử đào',
    singUp: 'Báo danh',
    noRank: 'Chưa có hạng',
    todayScore: 'Điểm phú hộ hôm nay:',
    totalScore: 'Tổng điểm phú hộ:',
    lastRank: 'Kém hạng trên:',
    todayTask: 'Nhiệm vụ ngày',
    todayNum: 'Lần đào',
    bar: 'Tiến độ',
    suc: 'Đã xong',
    day: 'ngày',
    tips1: 'Liên tiếp 5 ngày hoàn thành toàn bộ nhiệm vụ ngày sẽ nhận xe Ferrari (5 ngày)~',
    rechargeTitle: 'Nhiệm vụ nạp',
    rechargeToday: 'Hôm nay bạn đã nạp X xu',
    rechargeTips: 'Mỗi khi nạp đủ 50 xu nhận ngay 1 lần đào, nhận vô số điểm phú hộ để đổi quà',
    goRecharge: 'Nạp ngay',
    warsds: 'Phần thưởng mỗi ngày chỉ được nhận trong ngày, hôm sau sẽ mất',
    lv: 'Cấp',
    dayScore: 'Điểm phú hộ',
    wards: 'Phần thưởng',
    geted: 'Đã nhận',
    get: 'Nhận',
    getNo: 'Chưa đạt',
    lvUp: 'Chúc mừng đạt Lv.X',
    getTips: 'Bạn sẽ nhận',
    getBack: '(Phần thưởng tự động gửi, mời chú ý kiểm tra)',
    gameTips1: 'Còn cách 1 tầng~',
    gameTips2: 'Giải Cứu Thợ Mỏ',
    gameTips3: 'Số lần đào còn lại:',
    gameTips4: 'Giải cứu thành công nhận vô số điểm phú hộ!',
    go: 'Đào',
    noGo: 'Không thể đào!',
    noGoTips: 'Bạn đã hết lượt.</br>Mau làm nhiệm vụ để nhận thêm lượt đào~~',
    noGoTips2: 'Bạn chưa báo danh, sau khi báo danh mới được đào',
    goSuc: 'Giải cứu thành công',
    goSucTips: 'Chúc mừng bạn nhận được <em>X</em> điểm phú hộ',
    rankTips1: 'Điểm phú hộ = giá trị của quặng đào được',
    noDate: 'Chưa có số liệu!',
    score: 'điểm phú hộ：',
    dayWards: 'Thưởng ngày',
    rankTitle: 'BXH Phú Hộ',
    hsitoryTitle: 'Lịch sử đào',
    time: 'Thời gian',
    stone: 'Quặng',
    score2: 'điểm phú hộ',
    // noPeople: '清空礦池',
    getPeople: 'Giải Cứu Thợ Mỏ'
}
export default lang