// https://brushes8.com/zhong-wen-jian-ti-fan-ti-zhuan-huan
export default {
  title: 'Tìm kho báu',
  super_exchange: 'Đổi',
  treasure_map: 'Bản đồ kho báu',
  get: 'Được',
  treasure_one: 'Tìm 1 lần',
  treasure_ten: 'Tìm 10 lần',
  adventure_list: 'BXH',
  luck_value: 'Điểm may mắn',
  luck_value_tip: 'Điểm may mắn đạt 100 rồi tìm kho báu sẽ được kim cương màu',
  sure: 'Xác nhận',
  process_bottom_text: 'tìm kho báu',
  super_treasure_tip: 'Theo số lượng tìm kho báu của tấc cả người dùng mà tăng thêm tiến độ, đạt 100% nhập vào kiểu mẫu super tìm kho báu 1 giờ, giải thưởng càng phong phú!',
  time_down: 'Còn',
  time_down_value: '{0}:{1}',	
  hunt_get: 'Đã được',
  total: 'Tổng cộng %s cái',
  content_update: 'Cập nhật nội dung, mời thử lại',
  hunt_not_leave: 'Đang tìm kho báu, xin đừng rời đi',

  how_to_play: 'Thể lệ',
  treasure_hunt: 'Tìm kho báu',
  treasure_hunt_1: 'Tìm kho báu sẽ không ngừng cập nhật giải thưởng, 1 tấm bản đồ kho báu có thể tham gia 1 lần sự kiện và nhận 100 điểm thám hiểm, 10 tấm thì có thể tham gia 10 lần và nhận 1000 điểm thám hiểm.',
  treasure_hunt_2: '{2} tấm tiêu {1} xu, {4} tấm tiêu {3} xu, {6} tấm tiêu {5} xu.',
  lucky_moment: 'Giờ may mắn',
  lucky_moment_1: 'Mỗi lần tìm kho báu sẽ tăng Điểm may mắn, tìm 1 lần tăng 1 điểm, 10 lần tăng 10 điểm.',
  lucky_moment_2: 'Đạt 100 điểm sẽ hiện ra「Giờ may mắn」,lần sau tìm lại chắc chắn được kim cương màu, điểm may mắn thì trở về 0.',
  super_treasure_hunt: 'Super tìm kho báu',
  super_treasure_hunt_1: 'Tất cả người chơi tham gia sự kiện sẽ tăng tiến độ tìm kho báu, mỗi lần tăng %s；',
  super_treasure_hunt_2: 'Khi đạt tiến độ 100%, sẽ hiện ra kiểu mẫu 「Super tìm kho báu」với 1 tiếng đồng hồ',
  super_treasure_hunt_3: 'Trong kiểu mẫu「Super tìm kho báu」, tạm dừng tích điểm may mắn.',
  super_value_exchange: 'Đổi',
  super_value_exchange_1: 'Dùng vỏ sò, kim cương màu đổi dụng cụ đối ứng, dụng cụ sẽkhông ngừng cập nhật.',
  super_value_exchange_2: 'Qùa được đổi sẽ hiện thị trên túi quà, khung ảnh, xe sẽ hiện thịtrên shop tôi.',
  adventure_list_1: 'Mỗi tuần sẽ thông kê BXH theo điểm thám hiểm, 0 giờ thứ hai kết toán BXH tuần trước, BXH chỉ hiện thị top 50. ',
  adventure_list_2: 'Top 10 có thể được「Giải thưởng thám hiểm」',
  adventure_first: 'Top 1',
  adventure_first_des: 'Bộ Super tìm kho báu (chứng nhận+khung ảnh+xe+huy chương)7ngày',
  adventure_second: 'Top 2~3',
  adventure_second_des: 'Bộ tìm kho báu (khung ảnh+huy chương)7ngày',
  adventure_rest: 'Top 4~10',
  adventure_rest_des: 'Huy chương Tìm kho báu 7 ngày',
  prop_get_rate: 'Tỷ lệ được dụng cụ',
  general_treasure_hunt: 'Tìm kho báu bình thường',
  item_name: 'Tên',
  rate: 'Tỷ lệ(0.0001)',
  gift_1: 'Bảo kiếm',
  gift_2: 'Chìa khóa vàng',
  gift_3: 'Vỏ sò',
  gift_4: 'Qúy báu',
  gift_5: 'Vương miện',
  gift_6: 'Kim cương màu',
  gift_7: 'Du thuyền 7 ngày',
  gift_8: 'Tàu ngầm',
  gift_9: 'Vỏ sò X2',
  gift_10: 'Kim cương màu X2',
  gift_11: 'Tàu cướp biển',
  other_explain: 'Bổ sung khác',
  other_explain_1: 'Các dụng cụ nhận qua「Tìm kho báu」、「Đổi」có thời hạn chỉ định, vui lòng sử dụng kịp thời.',
  other_explain_2: 'Các dụng cụ đã được chỉ sử dụng trên app, không được mua bán, thu mua, nếu không sẽ bị phạt nặng',
  other_explain_3: 'Cấm tấc cả hành động ảnh hưởng tới sự công bằng về tương tác, hoặc tham gia sự kiện bằng cách không đúng đắn qua bug app, nếu bị phạt hiện, bên app có quyền hủy phát dụng cụ và thu lại',
  other_explain_4: 'Sự kiện không liên quan đến công ty Apple, các quyền cuối cùng thuộc về bên AloChat.',

  get_treasure_map: 'Được bản đồ kho báu',
  map_num: '%s tấm',
  get_map: 'Được',
  get_map_des: 'Tiêu {0} xu có thể được {1} tấm bản đồ kho báu',
  store: 'Nạp',
  coins_not_enough: 'Không đủ tiền',
  get_map_succ: 'Nhận được thành công',
  map_not_enough: 'Không đủ bản đồ kho báu',

  treasure_record: 'Lịch sử',
  record_time: '{0}.{1}.{2} {3}:{4}:{5}',
  use_map: 'Đã dùng %s tấm bản đồ kho báu',
  record_100: 'Tối đa hiện thị 100 lịch sử',
  loading: 'Đang tải...',
  not_record: 'Chưa có dữ liệu',

  more_select: 'Người được chọn nhiều nhất',
  exchange: 'Đổi',
  day: '%s ngày',
  exchange_succ: 'Đổi thành công',
  shell_not_enough: 'Đổi thất bại, không đủ vỏ sò',
  jewel_not_enough: 'Đổi thất bại, không đủ kim cương màu',

  adventure_list: 'BXH',
  weekly_award: 'Thưởng',
  weekly_award_title: '0 giờ mỗi thứ hai kết toán BXH, được thưởng tương ứng với BXH một lần tăng 100 điểm thám hiểm.',
  this_week: 'Tuần này',
  last_week: 'Tuần trước',
  list_adventure_value: '%s điểm thám hiểm',
  distance_last: 'Còn %s điểm so với top trên',
  not_data: 'Chưa có dữ liệu',
}