// https://brushes8.com/zhong-wen-jian-ti-fan-ti-zhuan-huan
export default {
    title: ' Nhiệm vụ Yêu và thưởng',

    envy_others: 'Ngưỡng mộ',
    current_cp_level: ' Cấp độ Yêu hiện tại',
    level_des: 'độ ngọt ngào:{0}, Tăng cấp cần {1}',
    
    coming_soon: 'Vui lòng chờ đợi',
    daily_cp_task: 'Nhiệm vụ Yêu mỗi ngày',
    daily_refresh: '0h mỗi ngày cập nhật lại',

    task_des_1: 'Mỗi người điểm danh %s%0 độ ngọt%1%0 ngào +10%1,Hai người điểm danh %s%0 độ ngọt ngào +100%1',
    task_des_2: 'Mỗi người điểm danh %s%0 độ ngọt%1%0 ngào +10%1,Hai người điểm danh %s%0 độ ngọt ngào +100%1',
    task_des_3: 'Mỗi cặp nhắn tin %s%0 độ ngọt ngào +1%1',
    task_des_4: 'cùng nhau trong 1 phòng mỗi phút %s%0 độ ngọt ngào +1%1',
    task_des_5: 'Gọi điện một lần',
    clock_in: 'Điểm danh ',
    clock_in_succ: 'Điểm danh thành công',

    cp_level: 'Cấp độ Yêu',
    cp_level_title_1: '1. Làm sao để tăng cấp độ Yêu？',
    cp_level_des_1: 'Cấp độ Yêu phụ thuộc độ ngọt ngào, Cấp độ yêu tương ứng với độ ngọt ngào theo bảng sau',
    cp_level_title_2: '2.Làm sao để tăng độ ngọt ngào？',
    cp_level_des_2: 'Độ ngọt ngào thông qua tặng quà, tặng nhẫn, hoàn thành nhiệm vụ Yêu. ',
    cp_level_title_3: '3. Sau khi đạt được cấp độ yêu nhận thưởng như thế nào？',
    cp_level_des_3: ' Sau khi tăng cấp độ Yêu, nếu có thưởng hiệu ứng sẽ tự động có hiệu lực; nếu có thưởng đạo cụ sẽ được gửi vào túi quà và sẽ có thông báo. ',
    love_value: 'Độ ngọt ngào',
    cp_table_title_1: 'Cảm tình',
    cp_table_title_2: 'Rung động',
    cp_table_title_3: 'Thân mật',
    cp_table_title_4: 'Lãng mạn',
    cp_table_title_5: 'Ngọt ngào',
    cp_table_title_6: 'Hạnh phúc',
    cp_table_value_1: '≥0',
    cp_table_value_2: '≥3300',
    cp_table_value_3: '≥7000',
    cp_table_value_4: '≥14500',
    cp_table_value_5: '≥30000',
    cp_table_value_6: '≥100000',

    cp_explain: 'Giải thích Yêu',
    explain_title_1: '1.Làm sao để có được Góc yêu？',
    explain_des_1: 'Sau khi bạn và người ấy trở thành một cặp sẽ có Góc yêu',
    explain_title_2: '2.Độ ngọt ngào dùng để làm gì？Làm sao tăng độ ngọt ngào？',
    explain_des_2: 'Độ ngọt ngào thể hiện tình yêu của hai bạn, và có thể giúp cho hai bạn tăng cấp mở đặc quyền CP. độ ngọt ngào thông qua tặng quà, tặng nhẫn, hoàn thành nhiệm vụ Yêu',
    explain_title_3: '3. Sau khi thoát khỏi Góc yêu, Góc yêu có còn không?',
    explain_des_3: 'Sau khi thoát khỏi góc yêu, hai bạn sẽ mất đi góc yêu của mình. Nếu sau đó hai bạn lại hợp đôi, góc yêu của các bạn sẽ được tính độ ngọt ngào trước đó (đương nhiên khi hai bạn thoát khỏi góc yêu độ ngọt ngào sẽ tạm dừng). ',
    explain_title_4: '4. Đổi nhẫn sẽ như thế nào？',
    explain_des_4: 'Sau khi trở thành một cặp, đổi nhẫn sẽ hiển thị nhẫn mới và thưởng động thái tương ứng với nhẫn hai bạn đang đeo, đồng thời có thể chọn nhẫn bất kỳ trong hộp nhẫn của bạn.',
}