export default {
    //html/index.html
    title: "天天開心鴨",
    act_rule: "規則&獎勵",
    feed_record: "投餵紀錄",
    user_duck: "%s的鴨鴨",
    award_title_1: "快樂小風車",
    award_title_2: "彩虹泡泡機",
    award_title_3: "真愛之吻",
    award_title_4: "音樂流雲",
    award_title_5: "烈焰戰車",
    award_title_6: "歐皇附體",
    award_title_7: "大家好鴨",
    award_title_8: "88金豆",
    award_title_9: "40金幣",
    award_des_1: "禮物",
    award_des_2: "動效禮物",
    award_des_3: "動效禮物",
    award_des_4: "頭像框(1天)",
    award_des_5: "座駕(7天)",
    award_des_6: "頭像框(3天)",
    award_des_7: "座駕(1天)",
    award_des: "用金幣購買糧食投餵鴨鴨，有機會獲得以下獎勵",
    duck_happy_value: "投餵次數",
    gift_title_1: "小貓咪-特效禮物",
    gift_title_2: "大家好鴨\n座駕(3天)",
    gift_title_3: "歐皇附體\n頭像框(7天）",
    my_coin: "我的金幣：%s",
    notice: "【{0}】收到開心鴨的禮物【{1}】",
    step_award_succ: "感謝主人投餵和陪伴！鴨鴨送你【%s】",

    toast_1: "我會一直陪伴你！",
    toast_2: "你也要按時吃飯啊",
    toast_3: "我要讓主人的桃花運變旺",
    toast_4: "明天也要來看我啊",
    toast_5: "肚子胖胖生活旺旺",
    toast_6: "鴨鴨的開心值達到就會送一份稀有禮物",
    toast_7: "希望每天都能給你帶來快樂",
    toast_8: "開心就要咔次咔次",
    toast_9: "好看的人會經常來給我投餵",
    toast_10: "偷偷告訴你聽說有人暗戀你",
    toast_11: "好看的人都會給我餵食",
    toast_12: "如果你給我投餵，我就送你一份禮物",

    happy_value: "開心值",
    first_dialog_des:
        "哈囉~主人，我是你的開心鴨，\n我可以每天陪你聊聊天\n投餵我，我會送你一份禮物哦>u<",
    award_dialog_des: "感謝主人的投喂\n主人的開心值增加%s",
    car_day: "-座駕(%s天)",
    frame_day: "-頭像框(%s天)",
    gift_day: "-動效禮物(%s天)",
    record: "投餵鴨鴨{1}次，收到{2}",
    time: "mm/dd HH:MM",
    bean: "%s金豆",
    coin: "%s金幣",
    loading: "加載中",
    coming_soon: "敬請期待",
    not_data: "暫無數據",
    use_coin_feed: "使用%s金幣投餵開心鴨",

    //rule
    act_time: "活動時間：%s",
    s_time: "YYYY/mm/dd HH:MM",
    e_time: "mm/dd HH:MM:SS",
    how_play: "1、如何和鴨鴨玩",
    how_play_des_1:
        "鴨鴨是一隻可愛又愛吃的小寵物，每天可以陪你聊聊天小互動，每當你對鴨鴨投餵，他就會送你一份禮物，雙方都可獲得開心值。",
    how_play_des_2: "當鴨鴨的投餵次數達到門檻，會送出指定獎勵",
    duck_gift: "2、鴨鴨的禮物",
    duck_gift_des_1: "鴨鴨有可能送出以下禮物",
    duck_gift_des_2: "*活動中的禮物有效期為7天，請盡快送出哦~",
    list_award: "3、開心榜獎勵",
    list_award_des_1:
        "第一名：風雲人物勛章（10天）+烈焰戰車-座駕（7天）+歐皇附體-頭像框（7天）",
    list_award_des_2:
        "第二名：風雲人物勛章（7天）+烈焰戰車-座駕（7天）+歐皇附體-頭像框（7天）",
    list_award_des_3:
        "第三名：風雲人物勛章（7天）+烈焰戰車-座駕（5天）+歐皇附體-頭像框（5天）",
    list_award_des_4: "第四-六名：歐皇附體-頭像框（3天）",
    apple: "*本活動與蘋果公司無關",
    explain: "*活動最終解釋權歸活動主辦方所有",
    rate_1: "50%",
    rate_2: "1%",
    rate_3: "1%",
    rate_4: "15%",
    rate_5: "0.001%",
    rate_6: "0.5%",
    rate_7: "0.5%",
    rate_8: "8.999%",
    rate_9: "23%"
};
