<template>
  <div class="standard">
    <h5>I. Overview</h5>
    <p>1.1 To strengthen the management of the platform's live content, promote the healthy and orderly development of the platform's audio and video services, create a good live webcast ecosystem,
      and provide users with a healthy and harmonious platform for talent display and enjoyment, the Platform's Live Streaming Agreement and Code of Conduct (or "this Agreement") is amended in
      accordance with relevant laws and regulations and other provisions of the platform.</p>
    <p>1.2 This Agreement applies to all individuals or organizations that produce live content using live streaming services on this platform (hereinafter collectively referred to as "platform
      streamers"), and the "live content" referred to in this agreement means the content produced by the production, release and dissemination of audio and video information provided by the live
      broadcast service of this platform. However, if the platform has formulated separate rules for the management of violations for specific categories of live content, and the specific rules
      conflict with this Agreement, within the applicable scope of such separate rules for the management of violations, such separate rules for the management of violations shall prevail. The
      platform may still decide to apply this Agreement to those parts not provided for in such separate regulations for the management of violations.</p>
    <p>1.3 References to examples in the rules and regulations of this Agreement are not meant to be exhaustive and are meant only to help you understand and avoid violations. Please do not attempt to
      find loopholes in the rules and regulations and implement them. Please understand the purpose of these rules and regulations and do not post content that you believe may be in violation of the
      rules and regulations.</p>
    <h5 class="mt">II. Rules and Regulations</h5>
    <p>2.1 The streamers of the platform must abide by the following rules and regulations, otherwise they will be punished accordingly. The severity of the violation is determined by the platform
      official based on objective factors such as the intention, time, subject and influence of the violation.</p>
    <p>2.2 The streamers of the platform is obliged to ensure a healthy and orderly live broadcast environment, and the streamers shall be responsible for all contents generated by using the live
      broadcast service, including but not limited to the live broadcast cover, live broadcast title, audience users, information on the sing on stage order, channel information, public screen
      comments, etc. If violations occur during the live broadcast, the platform official shall reserve the right to punish the violator and also the streamer in accordance with the fact of violation
      and the degree of its impact.</p>
    <p>2.3 It is strictly forbidden to produce, copy, publish, or disseminate information that contains the following illegal or unlawful acts.</p>
    <p>
      (1) Opposing the basic principles established by the Constitution;<br />
      (2) Endangering national security, leaking state secrets, subverting state power, or undermining national unity;<br />
      (3) Damaging national honor and interests;<br />
      (4) Distort, vilify, blasphemy, deny the deeds and spirits of heroes or martyrs, or insult, slander or otherwise infringe upon their names, portraits, reputation or honor;<br />
      (5) Promoting terrorism or extremism or inciting the implementation of terrorist or extremist activities<br />
      (6) Inciting ethnic hatred, ethnic discrimination and undermining national unity;<br />
      (7) Undermining national religious policies, promoting cults and feudal superstitions;<br />
      (8)Spreading rumors to disrupt the economic and social order;<br />
      (9)Disseminating obscenity, pornography, gambling, violence, murder, terror or abetting crimes;<br />
      (10) Insulting or defaming others, infringing on the reputation, privacy and other legitimate rights and interests of others;<br />
      (11) Other political topics that may cause or have caused adverse effects.
    </p>
    <p>2.4 Live content violating laws and regulations is strictly prohibited, such as:</p>
    <p>
      (1) Displaying and disseminating obscene and pornographic acts or contents;<br />
      (2) Displaying, participating in or holding gambling acts or content involving large amounts of money or high-value articles;<br />
      (3) Displaying all drug-related content such as drug samples, ways of taking or injecting drugs, explaining production, instigating attempts, etc.;<br />
      (4) Organizing, publicizing or inducing users to join pyramid schemes or unknown organizations suspected of pyramid schemes;<br />
      (5) Conduct or content that displays or sells weapons of mass destruction, illegal drugs or equipment and tools;<br />
      (6) Spreading and guiding suicide-inducing games;<br />
      (7) Intentionally injuring or endangering the safety of others;<br />
      (8) Eating, killing, collecting or selling wild or rare protected animals and plants, or maltreating animals;<br />
      (9) The use of party flags, party emblems, national flags, national emblems, national anthems and other symbols and content representing the image of the Party and the State, or the use of major
      national events, major anniversaries and the name of the State organs and their staff to launch live activities;<br />
      (10) Content that has been banned from broadcasting on the network blacklist;<br />
      (11) Other contents prohibited by laws and administrative regulations.
    </p>
    <p>2.5 It is strictly prohibited to use exaggerated titles or broadcast content seriously inconsistent with the titles, such as:</p>
    <p>
      (1) Misleading, deceptive, severe contrast and exaggerated covers and titles attract users to click;<br />
      (2) Covers or titles contain sexual implication, sexual advances, glorification of sex trade, sexual harassment, etc.;<br />
      (3) Other covers and titles that are useless, meaningless or contain illegal information.
    </p>
    <p>2.6 Infringement of others' legitimate rights and interests is strictly prohibited, such as:</p>
    <p>
      (1) Over-hype star gossip and entertainment gossip;<br />
      (2) Advocate the lifestyle such as money worship and extravagance;<br />
      (3) Discredit, slander and attack others (including users, streamers and the official platform), such as using metaphors (items, codes, etc.) to insult, satire, fabricate rumors, expose privacy,
      etc.;<br />
      (4) Persuade fans or visitors to harass or attack others, such as: inciting people to make trouble in other live rooms, malicious reporting other live rooms.
    </p>
    <p>2.7 It is strictly prohibited to make improper comments on natural disasters, major accidents and other disasters, such as:</p>
    <p>
      (1) Fabricating or spreading false or unverified dangerous situations, epidemic situations, disasters, warnings, hot current events, etc.;<br />
      (2) Releasing improper remarks such as joking or entertaining natural and man-made disasters or historical events;<br />
      (3) Posting negative remarks causing panic and anxiety to others.
    </p>
    <p>2.8 It is strictly prohibited to post any behavior or content that may easily lead to sexual association, such as sexual implications or sexual advances, such as:</p>
    <p>
      (1) Live performances involving sensitive parts such as breasts, inner thighs, buttocks, sexual organ contours, etc.;<br />
      (2) Using gestures and postures to achieve sexually suggestive purposes, such as touching the body, pulling clothing, licking and biting cucumbers, sucking bananas, hitting the buttocks,
      imitating masturbation gestures, etc.;<br />
      (3) Displaying sex-related items or other objects explicitly or implicitly for the purpose of sexual association, including but not limited to condoms, underwear, silk stockings, inflatable
      dolls, etc.;<br />
      (4) Displaying vulgar words, links, pictures, music and other information content;<br />
      (5) Demonstrating deliberate shooting from special angles, such as deliberately focusing on sensitive parts, shooting from the bottom up, tracking and shooting others, etc.;<br />
      (6) Direct or indirect descriptions of nudity, sexual organs and other sensitive parts, sexual behavior, sexual process, sexual posture and other topics that can easily cause sexual
      association;<br />
      (7) Promoting or glorifying sex crimes, sexual violence, sex trafficking, sexual harassment, sexual humiliation and other undesirable topics such as tutorials for taking unconscious people on
      the roadside to get a room, one-night stand tips, SM play, etc.;<br />
      (8) Topics that describe in detail sex trade venues, sex workers' experiences or sex trade tutorials, such as the price of people in the red light district of a certain area, etc.;<br />
      (9) Interactive games with sexually provocative or sexually suggestive behavior or content, such as guessing the color of underwear, slapping, spanking, etc.;<br />
      (10) Displaying privacy places, adult places or adult entertainment scenes, such as nightclubs, bars, sauna bath centers, KTV, adult products exhibitions, bathrooms, changing rooms, etc.;<br />
      (11) Live acts or contents that make people generate sexual association or sexual fantasy because of the bed, quilt, etc.;<br />
      (12) Other sexually suggestive or provocative behaviors or contents.
    </p>
    <p>2.9 It is strictly prohibited to show blood, horror, cruelty and other acts or contents that may cause physical and mental discomfort, such as:</p>
    <p>
      (1) Showing the process of animal slaughter;<br />
      (2) Displaying self-harm or self-mutilation, bloody violence, disgusting vulgarity and other uncomfortable behavior or content, such as blade cutting, eating live things, etc.;<br />
      (3) Video, game screen appears too bloody and violent content.
    </p>
    <p>3.0 Conduct or content that incites discrimination against a group of people or a region is strictly prohibited, such as:</p>
    <p>
      (1) Conducting behavior or content that mocks, ridicules, insults, or abuses specific groups of people such as women, people with disabilities, ethnic minorities, or a certain disease
      group;<br />
      (2) Participating in or creating the above topics and encouraging fans, visitors and users to participate in related topics, such as AIDS people should die, etc.;<br />
      (3) Producing or reposting material, pictures or texts concerning discrimination.
    </p>
    <p>3.1 It is strictly prohibited to publicize vulgar or kitsch content, such as:</p>
    <p>
      (1) Glorifying unhealthy values such as incestuous relationships, quirky hobbies, celebrity sex life and other undesirable values of behavior or content such as marital infidelity, polygamy,
      "daddy" relationship, pedophilia, etc.;<br />
      (2) Publicizing and beautifying the improper views on marriage and love, consumption and values, violating the moral bottom line and the order of public morality;<br />
      (3) Showing unhealthy life styles such as smoking and excessive drinking;<br />
      (4) Broadcasting in unsuitable places such as burial sites, bad marriage scenes and medical scenes.
    </p>
    <p>3.2 It is strictly prohibited to show behaviors or contents that may trigger minors to imitate unsafe behaviors and behaviors that violate social morality, induce minors to develop bad habits,
      etc., such as:</p>
    <p>
      (1) Involving minors appearing on camera or as the main part of a live broadcast without the presence or consent of a guardian;<br />
      (2) Inducing or abetting minors to recharge, reward, or conduct private transactions through various channels;<br />
      (3) Displaying behaviors or contents with certain risk without any safeguard measures and reminders, such as the use of open flame, setting off fireworks, simple food-making process, high
      altitude parkour, river diving, etc.;<br />
      (4) Other undesirable behaviors or contents that may cause imitation by minors.
    </p>
    <p>3.3 Rules of Live Content and Behavior</p>
    <p>3.3.1 Prohibit the live broadcast of current affairs and social news content;</p>
    <p>3.3.2 Prohibit the live broadcast of movies, television, athletic competitions and other content involving copyright, as well as the broadcast of unauthorized works and content without
      copyright owned by the streamers;</p>
    <p>3.3.3 Prohibit the live broadcast of anti-science and feudal superstition contents of anti-science and feudal superstition, such as fortune-telling, Buddha cards, geomantic omen, ouija board,
      bunshinsaba, etc.;</p>
    <p>3.3.4 Prohibit the live broadcast of any stock recommendation behavior in personal form, including and not limited to guiding users to sign stock speculation agreements, investment consultation
      contracts, charging advisory fees or guidance fees, and other behavior that uses live broadcast to illegally operate securities business or to facilitate illegal activities;</p>
    <p>3.3.5 Prohibit the live broadcast of games or video programs on the prohibited list;</p>
    <p>3.3.6 Prohibit any content that may involve the violation or exposure of citizens' personal privacy;</p>
    <p>3.3.7 Prohibit the live broadcast of motor vehicle drivers in the course of driving; the co-drivers shall not produce any interfering behavior to the driver during the driving process, and
      shall not violate traffic rules such as drunk driving, red light running, speeding, etc.;</p>
    <p>3.3.8 Prohibit the live broadcast of behavior that disrupts normal public order, such as making noise, damaging public facilities, entering forbidden shooting places for filming, etc.;</p>
    <p>3.3.9 Prohibit the display of restrained knives and instruments;</p>
    <p>3.4.0 Prohibit live broadcast of natural disasters and social emergencies that may cause threats to personal safety, such as: typhoons, earthquakes, floods, fires, car accidents, etc.;</p>
    <p>3.4.1 Live internet calls for the purpose of harassment and teasing are prohibited;</p>
    <p>3.4.2 Streamers shall inform the participants of the relevant live broadcasting facts and obtain their consent if they conduct interview or shooting activities. If they are explicitly refused
      by the photographer, they shall immediately stop the shooting and shall not molest, focus, tease or secretly take pictures;</p>
    <p>3.4.3 Prohibit low-quality, non-nutritious content, such as black screen, live broadcast of sleeping, long freeze frame, etc.</p>
    <p>3.5 Live Dress and Makeup Specification</p>
    <p>3.5.1 Prohibit men from going topless, women deliberately reveal the cleavage;</p>
    <p>3.5.2 Prohibit men wearing only triangular or quadrangle underwear and other suspected underwear, tight pants, and the waist of the pants shall not be lower than the hip bone;</p>
    <p>3.5.3 Prohibit female underwear lower than the pelvis, higher than the hip line;</p>
    <p>3.5.4 Prohibit the wearing of erotic uniforms, underwear, see-through clothing, corsets, halter tops, horizontal collars, deep V-necks, ultra-short skirts, umbilical cord-revealing clothing,
      etc.</p>
    <p>3.5.5 Prohibit dressing too revealing, using only bath towels, fabrics, sheets, etc. to wrap the body, or although wearing clothes but give people the visual impression of not dressed;</p>
    <p>3.5.6 Prohibit exaggeration of cross-dressing clothes, graffiti on the body or face, and exaggeration of vulgar makeup;</p>
    <p>3.5.7 Prohibit stuffing of sensitive parts and malicious pranks;</p>
    <p>3.5.8 Prohibit wearing clothes with illegal patterns or text information;</p>
    <p>3.5.9 Prohibit the large-scale display of tattoos on various body parts;</p>
    <p>3.5.10 Prohibit wearing the uniforms of state agencies and military forces for live entertainment purposes, such as: police uniforms, military camouflage uniforms, city security uniforms, etc.
    </p>
    <p>3.6 Live Action Specification</p>
    <p>3.6.1 Prohibit imitation of a variety of vulgar, pornographic movements, sounds or seductive and provocative performances, such as striptease, wet body dance, drawing circles on the hips, etc.;
    </p>
    <p>3.6.2 Prohibit sexually suggestive touching, pulling, licking, biting, patting and other actions with sexual connotations, or using props to draw the audience's attention to sensitive parts, or
      using sensitive parts of the body for games;</p>
    <p>3.6.3 Prohibit deliberately focusing the camera on sensitive parts;</p>
    <p>3.6.4 Avoid making movements with the risk of going naked. Streamers should avoid such actions in advance that may cause exposure risk, such as bending over, lifting legs high, separating legs,
      splitting, standing upside down, frequently switching sitting positions, etc.;</p>
    <p>3.6.5 Prohibit the display of insulting gestures and postures.</p>
    <p>3.7 Live Speech Specification</p>
    <p>3.7.1 Prohibit the discussion of politically sensitive topics and the playing or singing of the national anthem;</p>
    <p>3.7.2 Prohibit vulgar speech and leading to vulgar interaction in the live room;</p>
    <p>3.7.3 Prohibit the publicity of pornographic and vulgar content and the promotion of vulgar atmosphere among users, such as inducing streamers to talk about sexual topics;</p>
    <p>3.7.4 Prohibit the use of foul language such as swear words, dirty words and verbal abuse during the broadcast. Streamers should actively avoid the habitual bad language in their speech to
      avoid adverse and vulgar effects on the overall performance;</p>
    <p>3.7.5 Other topics or speech that may cause or have caused adverse effects.</p>
    <p>3.8 Platform Use Specification</p>
    <p>3.8.1 Prohibit false advertising and the sale of legally prohibited goods by any means, such as: medical equipment, medicine herbs, gambling, adult products, guns, knives, porn, cloud disk
      advertising, sex appliances, health care, tobacco, illegal drug ads and sexually transmitted diseases treatment ads and other related content;</p>
    <p>3.8.2 Prohibit taking the initiative or inciting to allow to place or publicize any advertising information on the unauthorized live screen, public screen in the customized information area;
    </p>
    <p>3.8.3 Prohibit carrying out commercial activities in the name of the platform without permission, or conducting live broadcasting in the name of media, TV stations, journalists, etc.;</p>
    <p>3.8.4 Prohibit unauthorized pirated broadcasting or re-broadcasting of content owned by others with intellectual property rights, such as the live content of other streamers, short videos made
      by others, unauthorized film and television works, etc.;</p>
    <p>3.8.5 It is prohibited to attack official personnel or the official platform in any way that may adversely affect the platform;</p>
    <p>3.9 Other live content that has an adverse impact on the platform.</p>
    <h5>III. Handling Mechanism</h5>
    <p>4.0 If there are violations or contents in the live broadcast as shown in [II Rules and Regulations], the official will send audio video service disable warning, kick out the live broadcast
      warning, interrupt or restrict the live broadcast function, delete the relevant violation information, restrict relevant resources, deduct or freeze the live broadcast revenue, block or
      permanently freeze the relevant account and live broadcast room, restrict or permanently restrict the relevant identity information to open the live broadcast in accordance with Article 2.1 of
      this Agreement; </p>
    <p>4.1 In addition to the above disposal methods, the platform official will reserve the right to actively report to the network blacklist and transfer to judicial authorities according to the
      seriousness of the violation.</p>
    <h5>IV. By-laws</h5>
    <p>1. This Agreement is issued by the official of the platform, and the final interpretation right shall be vested in the platform official, who shall have the right to amend this Agreement and
      make it effective upon public announcement.</p>
    <p>2. This Agreement shall take effect from the date of publication.</p>
    <p class="lastTm">January 5, 2021</p>

  </div>
</template>
<script>
export default {

}
</script>
<style lang="scss" scoped>
.standard {
  padding: 0 0.3rem 0.21rem;
  .mt {
    margin-top: 0.6rem;
  }
  h5 {
    font-size: 0.32rem;
    color: rgba(17, 17, 17, 1);
    margin: 0.3rem auto 0.16rem;
  }
  p {
    color: rgba(153, 153, 153, 1);
    font-size: 0.26rem;
    margin-bottom: 0.2rem;
  }
  .lastTm {
    text-align: right;
    margin-top: 0.5rem;
  }
}
</style>
