const lang = {
    noAct: 'Acara belum mulai',
    actEd: 'Acara udah selesai',
    ok: 'Ya',
    rules: 'Aturan&Hadiah',
    history: 'Catatan menggali',
    singUp: 'Mendaftar',
    noRank: 'Tidak dalam daftar',
    todayScore: 'Nilai kekayaan hari ini:',
    totalScore: 'Total nilai kekayaan:',
    lastRank: 'Jarak dari yg sebelumnya:',
    todayTask: 'Tugas Harian',
    todayNum: 'Jumlah gali',
    bar: 'Kemajuan ',
    suc: 'Selesaikan',
    tips1: 'Setiap 5 hari berturut-turut utk menyelesaikan semua tugas harian, Anda bisa mendapatkan Mount Ferrari (5 hari) Hadiah akan dikirim secara otomatis,silakan cek~',
    rechargeTitle: 'Tugas top up',
    rechargeToday: 'Hari ini Anda udah top up X koin emas',
    rechargeTips: 'Anda bisa mendapatkan 1 kali utk gali ketika setiap top up 50 koin emas, dapatkan nilai kekayaan melalui menggali mineral dan menyelamatkan penambang, dan menukarnya dengan hadiah',
    goRecharge: 'Top up dulu',
    warsds: 'Hadiah harian berlaku hari ini utk menerima,pd pukul 24:00:00 akan dihapus',
    lv: 'peringkat',
    dayScore: 'Nilai kekayaan hari ini',
    wards: 'Hadiah',
    geted: 'Udah menerima',
    get: 'Menerima',
    getNo: 'Belum mencapai',
    lvUp: 'Selamat atas Anda mencapai LV X',
    getTips: 'Kamu udah mendapatkan',
    getBack: '（Hadiah udah dikirim ke akunmu,silakan cek）',
    gameTips1: 'Kurang 1 lantai',
    gameTips2: 'Menyelamatkan Penambang',
    gameTips3: 'Kali yg menggali tersisa:',
    gameTips4: 'Menyelamatkan mereka bisa mendapat banyak nilai kekayaan',
    go: 'gali',
    noGo: 'Gak bisa gali',
    noGoTips: 'Jumlah kali gali gak cukup, gak bisa digali</br>Silakan selesai tugas utk menang kesempatan gali',
    noGoTips2: 'Kamu belum mendaftar, setelah mendaftar baru bisa gali',
    goSuc: 'Berhasil Menyelamatkan',
    goSucTips: 'Selamat mendapatkan <em>X</em> nilai kekayaan',
    rankTips1: 'Nilai kekayaan=total nilai kekayaan yg dihadiahi melalui menggali mineral dan menyelamatkan penambang',
    noDate: 'Sekarang belum ada data',
    score: 'nilai kekayaan:',
    dayWards: 'Hadiah harian',
    rankTitle: 'Daftar kekayaan',
    hsitoryTitle: 'Catatan menggali harta karun',
    time: 'Waktu',
    stone: 'Mineral',
    score2: 'nilai kekayaan',
    getPeople: 'Menyelamatkan Penambang',
    day: 'hari'
}
export default lang