const lang = {
    noAct: 'Acara belum dimulai',
    actEd: 'Acara telah berakhir',
    ok: 'Saya tahu',
    dTips1: 'Sekarang waktunya melempar botol, Anda bisa mulai melempar botol ~',
    dayNum: 'Jumlah mengambil botol yg tersedia hari ini:',
    gNumTips: 'X botol diambil',
    gANumTips: '(Ada X botol premium)',
    openBottle: 'Buka botolnya',
    dTime: 'Sekarang bukan waktu melempar botol<br/>Waktu melempar botol:X',
    gTime: 'Sekarang bukan waktu mengambil botol<br/>Waktu mengambil botol:X',
    noPlayer: 'Sumber daya belum dimuat,silakan coba lagi nanti ~',
    numOver: 'Jumlah kali mengambil botol saat ini telah habis~',
    me: 'Saya ',
    firend: 'Teman',
    noData: 'Saat belum ada data',
    change: 'Pilih',
    loading: 'Loading...',
    noFriend: 'Belum punya teman, buruan tambahkan!',
    near: 'Recently:',
    lookWork: 'Cek nyanyian',
    dSucess: 'Botol berhasil dilempar',
    dSongTips: 'Anda akan menerima pendengar dan perhatian ketika Anda melempar botol lagu.Semakin banyak org melempar botol lagu, semakin banyak pendengar, nyanyian yg berkualitas akan mendapatkan lebih banyak jumlah kali utk eksposur~',
    dSongTips2: 'Sistem akan secara cerdas mengalokasikan jumlah orang yang mendengarkan lagu dan durasinya, mencocokkan dengan audiens yang paling mungkin tertarik pd nyanyian ini utk lakukan melempar, dan nyanyian yg berkualitas akan mendapatkan lebih banyak jumlah kali utk eksposur ~',
    again: 'Cek nyanyian',
    freeDb: 'Lempar botol dgn gratis',
    bayDb: 'Lempar botol dgn khusus',
    freeOver: 'Melempar botol dgn gratis telah digunakan hari ini',
    questTips: 'Pengguna pertama kali melempar botol dgn gratis tiap hari. Apakah Anda yakin melempar botol utk nyanyian ini?',
    qureyD: 'Ya',
    dNum: 'Jumlah org yg lempar',
    coins: 'Koin emas',
    coios2: 'Koin emas',
    bean: 'kacang emas',
    ok2: 'Ya',
    cancel: 'Batalkan',
    goStored: 'Top up ',
    songError: 'Audio memuat gagal, coba lagi nanti',

}
export default lang