const lang = {
    noAct: '活動未開始',
    actEd: '活動已結束',
    ok: '確認',
    dTips1: '現在是投瓶時間，可以開始投瓶',
    dayNum: '今日可撈取的次數:',
    gNumTips: '撈取了X個瓶子',
    gANumTips: '(有X個高級瓶子)',
    openBottle: '打開瓶子',
    dTime: '現在不是投瓶時間<br/>投瓶時間為X',
    gTime: '現在不是撈瓶時間<br/>撈瓶時間為X',
    noPlayer: '資源未加載完成，請稍後再試~',
    numOver: '當前撈瓶次數已用完~',
    me: '我的',
    firend: '好友',
    noData: '暫無數據',
    change: '選擇',
    loading: '加載中...',
    noFriend: '暫無好友，快去添加吧！',
    near: '近期：',
    lookWork: '查看作品',
    dSucess: '已投瓶成功',
    dSongTips: '投放歌曲會收到收聽和關注~投放的人數越多，<br />收聽歌曲的人越多，優質作品將得到更多曝光次數~',
    again: '重新選擇',
    freeDb: '免費投瓶',
    bayDb: '定製投瓶',
    freeOver: '今日免費投瓶已使用',
    questTips: '每位用戶每天首次投瓶免費，是否確認對此作品投瓶？',
    qureyD: '確認投瓶',
    dNum: '投放人數',
    coins: '金幣：',
    coios2: '金幣',
    bean: '金豆',
    ok2: '確定',
    cancel: '取消',
    goStored: '前去儲值',
    songError: '音頻加載失敗，請稍後再試',

}
export default lang