// const lang = {
//     // noAct: '活動未開始',
//     // actEd: '活動已結束',
//     ok: 'Xác nhận',
//     rules: 'Cách dự tiệc',
//     myAct: 'Tiệc của tôi',
//     creatAct: 'Đăng ký',
//     noActData: 'Chưa có số liệu！',
//     officialAct: 'App tổ chức',
//     firePeople: 'Người tổ chức:',
//     kRoom: 'Phòng tổ chức:',
//     date: 'Thời gian:',
//     peopleTips: 'người tham dự',
//     singUp: 'Báo danh',
//     actDetil: 'Chi tiết',
//     attention: '+Theo dõi',
//     attention2: 'Bỏ theo dõi',
//     rid: 'Phòng:',
//     actTips: 'Giới thiệu',
//     actGifts: 'Phần thưởng',
//     goRoom: 'Tham gia',
//     singUpTips1: 'Điền giới thiệu để gửi báo danh',
//     singUpTips2: 'Người tổ chức sẽ liên hệ bạn sớm nhất có thể,<br/>Vui lòng viết lời giới thiều rồi chờ đợi hồi âm.',
//     singUpTips3: 'Tôi có 2131 fan, sở trường hát nhạc trẻ, bài hát ưng ý nhất là “Sóng Gió” của Jack, rất mong được tham gia đêm nhạc do bạn tổ chức để mang giọng ca của tôi phục vụ khán giả. (ví dụ tham khảo)',
//     singUpTipsCom: 'Báo danh',
//     actBarTitle: 'Tiến độ duyệt',
//     actBarTips1: 'Đang đợi',
//     actBarTips2: 'Đang duyệt',
//     actBarTips3: 'Bị từ chối!',
//     actBarTips4: 'Đã duyệt',
//     actBarTips5: 'Đánh giá:',
//     actBarTips6: 'nội dung rất xuất sắc, hãy kêu gọi bạn bè tham gia nhé！',
//     actBarChang: 'Chỉnh sửa',
//     singUpDetil: 'Thông tin',
//     singUpNoData: ' Chưa có ai báo danh, nhanh đi mời bạn bè nào!',
//     singUpMsg: 'Giới thiệu',
//     ms: 'Gửi tin'
// }
const lang = {
    // noAct: '活動未開始',
    // actEd: '活動已結束',
    ok: 'Xác nhận',
    rules: 'Cách dự tiệc',
    myAct: 'Tiệc của tôi',
    creatAct: 'Đăng ký',
    noActData: 'Chưa có dữ liệu',
    officialAct: 'Chính thức',
    firePeople: 'Người tổ chức: ',
    kRoom: 'Phòng tổ chức: ',
    date: 'Thời gian: ',
    peopleTips: ' Người tham dự',
    singUp: 'Báo danh',
    actDetil: 'Chi tiết',
    attention: 'Theo dõi',
    attention2: 'Bỏ theo dõi',
    rid: 'Phòng: ',
    actTips: 'Giới thiệu: ',
    actGifts: 'Phần thưởng: ',
    goRoom: 'Tham gia',
    singUpTips1: 'Báo danh dự tiệc',
    singUpTips2: 'Hãy viết mấy câu để xin phép dụ tiệc.<br/>Người tổ chức sẽ liên hệ bạn sớm nhất có thể.',
    singUpTips3: 'Chào bạn, tôi xin báo danh tham gia dụ tiệc của bạn, chúc tiệc bạn tổ chức thành công và mọi người dự tiệc vui vẻ.',
    singUpTipsCom: 'Báo danh',
    actBarTitle: 'Tiến độ duyệt',
    actBarTips1: 'Đang đợi',
    actBarTips2: 'Đang duyệt',
    actBarTips3: 'Bị từ chối',
    actBarTips4: 'Đã duyệt',
    actBarTips5: 'Đánh giá: ',
    actBarTips6: 'Nội dung rất xuất sắc, hãy mời bạn bè tham gia nhé! ',
    actBarChang: 'Chỉnh sửa',
    singUpDetil: 'Thông tin',
    singUpNoData: ' Chưa có ai báo danh, mời bạn bè nào!',
    singUpMsg: 'Lời xin phép',
    ms: 'Gửi tin'
}
export default lang