const lang = {
    noAct: 'Belum mulai',
    actEd: 'Sudah berakhir',
    rule: 'Keterangan Aktivitas    ',
    history: 'Catatan Tukar    ',
    rule1: '1. Selama aktivitas, konten hari akan dibuka sesuai dengan jumlah hari, dan konten hari yang belum dibuka tidak dapat dilihat sebelumnya;    ',
    rule2: '2. Hadiah hanya dapat diterima pada hari yang sama, dan tidak berlaku setelah kedaluwarsa;    ',
    rule3: '3. Harap tukarkan hadiah tepat waktu selama waktu aktivitas, dan hadiah akan dihapus secara otomatis setelah kedaluwarsa;    ',
    task: 'Tugas    ',
    convertibility: 'Tukar    ',
    loading: ' Memuat...',
    noOpen: 'Belum mulai, silakan ditunggu!',
    loginTitle: 'Profit login hari ini    ',
    nowDayTitle: 'Tugas hari ini',
    receive: 'Terima',
    dayTasksTitle: 'Tugas hari ini',
    converGiftTitle: 'Tukar Hadiah    ',
    converNum: 'Anda dapat menukar paling banyak X tiap hari! ',
    converNum2: 'Anda dapat menukar paling banyak X tiap hari!    ',
    dayEd: 'Hari ini telah tukar    ',
    singUp: 'Segera Mendaftar    ',
    ok: 'Ya    ',
    // noSingUp: 'Mời báo danh trước~',
    openBoxTime: 'Waktu    ',
    gift: 'Hadiah    ',
    historyTitle: 'Catatan Tukar    ',
    singUpSuc: 'Berhasil Mendaftar    ',
    noSuc: 'Blm selesai',
    dayNoOpen: 'Belum mulai, silakan ditunggu!    ',
    noChpin: 'Fragmen Anda tidak cukup, cepat dapatkan!',
    noDayRev: 'Profit harian dan hadiah tugas hanya dapat diterima pada hari itu!    ',
    noData: "Tidak ada data!"
}
export default lang
