// https://brushes8.com/zhong-wen-jian-ti-fan-ti-zhuan-huan
export default {
    title: 'Tugas dan hadiah CP',

    envy_others: 'Membuat orang sangat kagum',
    current_cp_level: 'Level CP saat ini',
    level_des: 'Nilai manis：{0}，Masih perlu {1} akan tingkat ',
    
    coming_soon: 'Tetap disini',
    daily_cp_task: 'Tugas CP tiap hari',
    daily_refresh: 'Refresh setiap hari pada pukul 00:00',

    task_des_1: 'Sign in tunggal %s%0 nilai manis+10%1,Sign in double%s%0nilai manis+100%1',
    task_des_2: 'Sign in tunggal%s%0 nilai manis+10%1,Sign in double%s%0 nilai manis+100%1',
    task_des_3: 'Setiap pesan%s%0 nilai manis+1%1',
    task_des_4: 'Tiap menit %s%0 nilai manis+1%1 di kamar yang sama',
    task_des_5: 'Lakukan panggilan suara sekali',
    clock_in: 'Sign in',
    clock_in_succ: 'Sign in sukses',

    cp_level: 'Level CP',
    cp_level_title_1: '1. Bagaimana cara tingkatkan level CP?',
    cp_level_des_1: 'Level CP meningkat sesuai dengan nilai manisnya.Hubungan antara level CP dan nilai manis adalah sebagai berikut',
    cp_level_title_2: '2.Bagaimana cara tingkatkan nilai manis? ',
    cp_level_des_2: 'Nilai manis dapat ditingkatkan dengan saling memberi hadiah, membeli cincin baru, menerima hadiah berkah, dan selesaikan tugas CP.',
    cp_level_title_3: '3.Bagaimana cara dapatkan hadiah setelah naik level?',
    cp_level_des_3: 'Jika ada hadiah efek khusus yang sesuai akan berlaku secara otomatis setelah level ditingkatkan；ika ada hadiah alat peraga, itu akan secara otomatis dikirim ke ransel Anda, dan Asisten akan kirim pengingat pesan ke Anda！',
    love_value: 'Nilai manis',
    cp_table_title_1: 'Level CP 0',
    cp_table_title_2: 'Level CP 1',
    cp_table_title_3: 'Level CP 2',
    cp_table_title_4: 'Level CP 3',
    cp_table_title_5: 'Level CP 4',
    cp_table_title_6: 'Level CP 5',
    cp_table_value_1: '≥0',
    cp_table_value_2: '≥3300',
    cp_table_value_3: '≥7000',
    cp_table_value_4: '≥14500',
    cp_table_value_5: '≥30000',
    cp_table_value_6: '≥100000',

    cp_explain: 'Keterangan CP',
    explain_title_1: '1.Bagaimana cara memiliki CP House sendiri?',
    explain_des_1: 'Anda sekalian dapat memiliki  CP House setelah Anda dan favoritmu menjadi CP',
    explain_title_2: '2.Apa gunanya nilai manisnya? Bagaimana cara tingkatkan nilai manisnya?',
    explain_des_2: 'Nilai manis dapat membawa peningkatan hubungan CP untuk membuka hak istimewa baru hubungan CP ；Nilai manisnya dapat ditingkatkan dengan saling memberi hadiah, membeli cincin baru, dan selesaikan tugas CP',
    explain_title_3: '3.Apakah CP House masih ada tidak setelah hubungan CP diputus?',
    explain_des_3: 'Setelah akhiri hubungan CP, untuk sementara Anda sekalian akan kehilangan CP House.Namun nanti jika Anda sekalian kembali jadi hubungan CP (pengakuan ulang), akan dapat lanjutkan halaman CP sebelumnya dan nilai manis yang sesuai(Tentu saja, nilai manis Anda sekalian akan berhenti tumbuh setelah hubungan CP diputuskan)',
    explain_title_4: '4.Apa efek jika ganti cincin?',
    explain_des_4: 'Setelah menjadi CP, mengganti cincin akan menggantikan cincin lama dgn cincin baru, dan dapatkan hadiah numerik yg dibawa oleh cincin baru.Pada saat yang sama, Anda juga dapat memilih cincin favorit Anda di kotak cincin.',
}